// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class CluborbitMatrixNative
    extends
        BaseEntrypoint<
          CluborbitMatrixNativeApi,
          CluborbitMatrixNativeApiImpl,
          CluborbitMatrixNativeWire
        > {
  @internal
  static final instance = CluborbitMatrixNative._();

  CluborbitMatrixNative._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    CluborbitMatrixNativeApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required CluborbitMatrixNativeApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<CluborbitMatrixNativeApiImpl, CluborbitMatrixNativeWire>
  get apiImplConstructor => CluborbitMatrixNativeApiImpl.new;

  @override
  WireConstructor<CluborbitMatrixNativeWire> get wireConstructor =>
      CluborbitMatrixNativeWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 2062686299;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'cluborbit_matrix_native',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class CluborbitMatrixNativeApi extends BaseApi {
  Future<PendingRequest?> crateCryptoSessionBackupRoomKeys({
    required CryptoSession that,
  });

  Future<CrossSigningBootstrap> crateCryptoSessionBootstrapCrossSigning({
    required CryptoSession that,
    required String password,
  });

  Future<CryptoSession> crateCryptoSessionCreate({
    required String userId,
    required String deviceId,
    required String storePath,
    required String passphrase,
  });

  Future<String> crateCryptoSessionDecryptRoomEvent({
    required CryptoSession that,
    required String roomId,
    required String eventJson,
  });

  Future<String> crateCryptoSessionDeviceId({required CryptoSession that});

  Future<bool> crateCryptoSessionEnableKeyBackupFromSecret({
    required CryptoSession that,
    required String decryptionKeyBase64,
    required String versionInfoJson,
  });

  Future<String> crateCryptoSessionEncryptRoomEvent({
    required CryptoSession that,
    required String roomId,
    required String eventType,
    required String contentJson,
  });

  Future<PendingRequest?> crateCryptoSessionEnsureSessionsForUsers({
    required CryptoSession that,
    required List<String> userIds,
  });

  Future<CrossSigningSecrets?> crateCryptoSessionExportCrossSigningKeys({
    required CryptoSession that,
  });

  Future<IdentityKeys> crateCryptoSessionIdentityKeys({
    required CryptoSession that,
  });

  Future<bool> crateCryptoSessionImportCrossSigningKeys({
    required CryptoSession that,
    String? masterKey,
    String? selfSigningKey,
    String? userSigningKey,
  });

  Future<int> crateCryptoSessionImportRoomKeysFromBackup({
    required CryptoSession that,
    required String keysResponseJson,
  });

  Future<bool> crateCryptoSessionIsCrossSigningReady({
    required CryptoSession that,
  });

  Future<bool> crateCryptoSessionIsKeyBackupEnabled({
    required CryptoSession that,
  });

  Future<void> crateCryptoSessionMarkRequestAsSent({
    required CryptoSession that,
    required String id,
    required String kind,
    required String responseJson,
  });

  Future<NewKeyBackup> crateCryptoSessionNewKeyBackup({
    required CryptoSession that,
  });

  Future<List<PendingRequest>> crateCryptoSessionOutgoingRequests({
    required CryptoSession that,
  });

  Future<List<String>> crateCryptoSessionReceiveSyncChanges({
    required CryptoSession that,
    required List<String> toDeviceEventsJson,
    required List<String> changedDeviceUsers,
    required List<String> leftDeviceUsers,
    required List<(String, BigInt)> oneTimeKeyCounts,
  });

  Future<RoomKeyCountsInfo> crateCryptoSessionRoomKeyCounts({
    required CryptoSession that,
  });

  Future<List<PendingRequest>> crateCryptoSessionShareRoomKey({
    required CryptoSession that,
    required String roomId,
    required List<String> userIds,
  });

  Future<void> crateCryptoSessionUpdateTrackedUsers({
    required CryptoSession that,
    required List<String> userIds,
  });

  Future<Uint8List> crateDecryptAttachment({
    required List<int> ciphertext,
    required String keyBase64,
    required String ivBase64,
    String? sha256Base64,
  });

  Future<EncryptedAttachment> crateEncryptAttachment({
    required List<int> plaintext,
  });

  Future<String> crateNativeCryptoEngineVersion();

  Future<bool> crateSsssCheckMasterKey({
    required List<int> masterKey,
    required String checkIvBase64,
    required String expectedMacBase64,
  });

  Future<NewSecretStorageKey> crateSsssCreateKeyFromPassphrase({
    required String passphrase,
  });

  Future<String> crateSsssDecryptSecret({
    required List<int> masterKey,
    required String secretName,
    required String ivBase64,
    required String ciphertextBase64,
    required String macBase64,
  });

  Future<Uint8List> crateSsssDeriveMasterKey({
    required String passphrase,
    required String salt,
    required int iterations,
  });

  Future<EncryptedSecret> crateSsssEncryptSecret({
    required List<int> masterKey,
    required String secretName,
    required String plaintext,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CryptoSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CryptoSession;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CryptoSessionPtr;
}

class CluborbitMatrixNativeApiImpl extends CluborbitMatrixNativeApiImplPlatform
    implements CluborbitMatrixNativeApi {
  CluborbitMatrixNativeApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<PendingRequest?> crateCryptoSessionBackupRoomKeys({
    required CryptoSession that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_pending_request,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateCryptoSessionBackupRoomKeysConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionBackupRoomKeysConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoSession_backup_room_keys",
        argNames: ["that"],
      );

  @override
  Future<CrossSigningBootstrap> crateCryptoSessionBootstrapCrossSigning({
    required CryptoSession that,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
            that,
            serializer,
          );
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_cross_signing_bootstrap,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateCryptoSessionBootstrapCrossSigningConstMeta,
        argValues: [that, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionBootstrapCrossSigningConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoSession_bootstrap_cross_signing",
        argNames: ["that", "password"],
      );

  @override
  Future<CryptoSession> crateCryptoSessionCreate({
    required String userId,
    required String deviceId,
    required String storePath,
    required String passphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(storePath, serializer);
          sse_encode_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateCryptoSessionCreateConstMeta,
        argValues: [userId, deviceId, storePath, passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionCreateConstMeta => const TaskConstMeta(
    debugName: "CryptoSession_create",
    argNames: ["userId", "deviceId", "storePath", "passphrase"],
  );

  @override
  Future<String> crateCryptoSessionDecryptRoomEvent({
    required CryptoSession that,
    required String roomId,
    required String eventJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
            that,
            serializer,
          );
          sse_encode_String(roomId, serializer);
          sse_encode_String(eventJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateCryptoSessionDecryptRoomEventConstMeta,
        argValues: [that, roomId, eventJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionDecryptRoomEventConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoSession_decrypt_room_event",
        argNames: ["that", "roomId", "eventJson"],
      );

  @override
  Future<String> crateCryptoSessionDeviceId({required CryptoSession that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateCryptoSessionDeviceIdConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionDeviceIdConstMeta => const TaskConstMeta(
    debugName: "CryptoSession_device_id",
    argNames: ["that"],
  );

  @override
  Future<bool> crateCryptoSessionEnableKeyBackupFromSecret({
    required CryptoSession that,
    required String decryptionKeyBase64,
    required String versionInfoJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
            that,
            serializer,
          );
          sse_encode_String(decryptionKeyBase64, serializer);
          sse_encode_String(versionInfoJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateCryptoSessionEnableKeyBackupFromSecretConstMeta,
        argValues: [that, decryptionKeyBase64, versionInfoJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionEnableKeyBackupFromSecretConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoSession_enable_key_backup_from_secret",
        argNames: ["that", "decryptionKeyBase64", "versionInfoJson"],
      );

  @override
  Future<String> crateCryptoSessionEncryptRoomEvent({
    required CryptoSession that,
    required String roomId,
    required String eventType,
    required String contentJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
            that,
            serializer,
          );
          sse_encode_String(roomId, serializer);
          sse_encode_String(eventType, serializer);
          sse_encode_String(contentJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateCryptoSessionEncryptRoomEventConstMeta,
        argValues: [that, roomId, eventType, contentJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionEncryptRoomEventConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoSession_encrypt_room_event",
        argNames: ["that", "roomId", "eventType", "contentJson"],
      );

  @override
  Future<PendingRequest?> crateCryptoSessionEnsureSessionsForUsers({
    required CryptoSession that,
    required List<String> userIds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
            that,
            serializer,
          );
          sse_encode_list_String(userIds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_pending_request,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateCryptoSessionEnsureSessionsForUsersConstMeta,
        argValues: [that, userIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionEnsureSessionsForUsersConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoSession_ensure_sessions_for_users",
        argNames: ["that", "userIds"],
      );

  @override
  Future<CrossSigningSecrets?> crateCryptoSessionExportCrossSigningKeys({
    required CryptoSession that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_cross_signing_secrets,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateCryptoSessionExportCrossSigningKeysConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionExportCrossSigningKeysConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoSession_export_cross_signing_keys",
        argNames: ["that"],
      );

  @override
  Future<IdentityKeys> crateCryptoSessionIdentityKeys({
    required CryptoSession that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_keys,
          decodeErrorData: null,
        ),
        constMeta: kCrateCryptoSessionIdentityKeysConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionIdentityKeysConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoSession_identity_keys",
        argNames: ["that"],
      );

  @override
  Future<bool> crateCryptoSessionImportCrossSigningKeys({
    required CryptoSession that,
    String? masterKey,
    String? selfSigningKey,
    String? userSigningKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
            that,
            serializer,
          );
          sse_encode_opt_String(masterKey, serializer);
          sse_encode_opt_String(selfSigningKey, serializer);
          sse_encode_opt_String(userSigningKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateCryptoSessionImportCrossSigningKeysConstMeta,
        argValues: [that, masterKey, selfSigningKey, userSigningKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionImportCrossSigningKeysConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoSession_import_cross_signing_keys",
        argNames: ["that", "masterKey", "selfSigningKey", "userSigningKey"],
      );

  @override
  Future<int> crateCryptoSessionImportRoomKeysFromBackup({
    required CryptoSession that,
    required String keysResponseJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
            that,
            serializer,
          );
          sse_encode_String(keysResponseJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateCryptoSessionImportRoomKeysFromBackupConstMeta,
        argValues: [that, keysResponseJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionImportRoomKeysFromBackupConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoSession_import_room_keys_from_backup",
        argNames: ["that", "keysResponseJson"],
      );

  @override
  Future<bool> crateCryptoSessionIsCrossSigningReady({
    required CryptoSession that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateCryptoSessionIsCrossSigningReadyConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionIsCrossSigningReadyConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoSession_is_cross_signing_ready",
        argNames: ["that"],
      );

  @override
  Future<bool> crateCryptoSessionIsKeyBackupEnabled({
    required CryptoSession that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateCryptoSessionIsKeyBackupEnabledConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionIsKeyBackupEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoSession_is_key_backup_enabled",
        argNames: ["that"],
      );

  @override
  Future<void> crateCryptoSessionMarkRequestAsSent({
    required CryptoSession that,
    required String id,
    required String kind,
    required String responseJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          sse_encode_String(kind, serializer);
          sse_encode_String(responseJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateCryptoSessionMarkRequestAsSentConstMeta,
        argValues: [that, id, kind, responseJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionMarkRequestAsSentConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoSession_mark_request_as_sent",
        argNames: ["that", "id", "kind", "responseJson"],
      );

  @override
  Future<NewKeyBackup> crateCryptoSessionNewKeyBackup({
    required CryptoSession that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_new_key_backup,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateCryptoSessionNewKeyBackupConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionNewKeyBackupConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoSession_new_key_backup",
        argNames: ["that"],
      );

  @override
  Future<List<PendingRequest>> crateCryptoSessionOutgoingRequests({
    required CryptoSession that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_pending_request,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateCryptoSessionOutgoingRequestsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionOutgoingRequestsConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoSession_outgoing_requests",
        argNames: ["that"],
      );

  @override
  Future<List<String>> crateCryptoSessionReceiveSyncChanges({
    required CryptoSession that,
    required List<String> toDeviceEventsJson,
    required List<String> changedDeviceUsers,
    required List<String> leftDeviceUsers,
    required List<(String, BigInt)> oneTimeKeyCounts,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
            that,
            serializer,
          );
          sse_encode_list_String(toDeviceEventsJson, serializer);
          sse_encode_list_String(changedDeviceUsers, serializer);
          sse_encode_list_String(leftDeviceUsers, serializer);
          sse_encode_list_record_string_u_64(oneTimeKeyCounts, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateCryptoSessionReceiveSyncChangesConstMeta,
        argValues: [
          that,
          toDeviceEventsJson,
          changedDeviceUsers,
          leftDeviceUsers,
          oneTimeKeyCounts,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionReceiveSyncChangesConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoSession_receive_sync_changes",
        argNames: [
          "that",
          "toDeviceEventsJson",
          "changedDeviceUsers",
          "leftDeviceUsers",
          "oneTimeKeyCounts",
        ],
      );

  @override
  Future<RoomKeyCountsInfo> crateCryptoSessionRoomKeyCounts({
    required CryptoSession that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_room_key_counts_info,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateCryptoSessionRoomKeyCountsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionRoomKeyCountsConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoSession_room_key_counts",
        argNames: ["that"],
      );

  @override
  Future<List<PendingRequest>> crateCryptoSessionShareRoomKey({
    required CryptoSession that,
    required String roomId,
    required List<String> userIds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
            that,
            serializer,
          );
          sse_encode_String(roomId, serializer);
          sse_encode_list_String(userIds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_pending_request,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateCryptoSessionShareRoomKeyConstMeta,
        argValues: [that, roomId, userIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionShareRoomKeyConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoSession_share_room_key",
        argNames: ["that", "roomId", "userIds"],
      );

  @override
  Future<void> crateCryptoSessionUpdateTrackedUsers({
    required CryptoSession that,
    required List<String> userIds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
            that,
            serializer,
          );
          sse_encode_list_String(userIds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateCryptoSessionUpdateTrackedUsersConstMeta,
        argValues: [that, userIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoSessionUpdateTrackedUsersConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoSession_update_tracked_users",
        argNames: ["that", "userIds"],
      );

  @override
  Future<Uint8List> crateDecryptAttachment({
    required List<int> ciphertext,
    required String keyBase64,
    required String ivBase64,
    String? sha256Base64,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(ciphertext, serializer);
          sse_encode_String(keyBase64, serializer);
          sse_encode_String(ivBase64, serializer);
          sse_encode_opt_String(sha256Base64, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateDecryptAttachmentConstMeta,
        argValues: [ciphertext, keyBase64, ivBase64, sha256Base64],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateDecryptAttachmentConstMeta => const TaskConstMeta(
    debugName: "decrypt_attachment",
    argNames: ["ciphertext", "keyBase64", "ivBase64", "sha256Base64"],
  );

  @override
  Future<EncryptedAttachment> crateEncryptAttachment({
    required List<int> plaintext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_encrypted_attachment,
          decodeErrorData: null,
        ),
        constMeta: kCrateEncryptAttachmentConstMeta,
        argValues: [plaintext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateEncryptAttachmentConstMeta => const TaskConstMeta(
    debugName: "encrypt_attachment",
    argNames: ["plaintext"],
  );

  @override
  Future<String> crateNativeCryptoEngineVersion() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateNativeCryptoEngineVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateNativeCryptoEngineVersionConstMeta =>
      const TaskConstMeta(
        debugName: "native_crypto_engine_version",
        argNames: [],
      );

  @override
  Future<bool> crateSsssCheckMasterKey({
    required List<int> masterKey,
    required String checkIvBase64,
    required String expectedMacBase64,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(masterKey, serializer);
          sse_encode_String(checkIvBase64, serializer);
          sse_encode_String(expectedMacBase64, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateSsssCheckMasterKeyConstMeta,
        argValues: [masterKey, checkIvBase64, expectedMacBase64],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSsssCheckMasterKeyConstMeta => const TaskConstMeta(
    debugName: "ssss_check_master_key",
    argNames: ["masterKey", "checkIvBase64", "expectedMacBase64"],
  );

  @override
  Future<NewSecretStorageKey> crateSsssCreateKeyFromPassphrase({
    required String passphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_new_secret_storage_key,
          decodeErrorData: null,
        ),
        constMeta: kCrateSsssCreateKeyFromPassphraseConstMeta,
        argValues: [passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSsssCreateKeyFromPassphraseConstMeta =>
      const TaskConstMeta(
        debugName: "ssss_create_key_from_passphrase",
        argNames: ["passphrase"],
      );

  @override
  Future<String> crateSsssDecryptSecret({
    required List<int> masterKey,
    required String secretName,
    required String ivBase64,
    required String ciphertextBase64,
    required String macBase64,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(masterKey, serializer);
          sse_encode_String(secretName, serializer);
          sse_encode_String(ivBase64, serializer);
          sse_encode_String(ciphertextBase64, serializer);
          sse_encode_String(macBase64, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateSsssDecryptSecretConstMeta,
        argValues: [
          masterKey,
          secretName,
          ivBase64,
          ciphertextBase64,
          macBase64,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSsssDecryptSecretConstMeta => const TaskConstMeta(
    debugName: "ssss_decrypt_secret",
    argNames: [
      "masterKey",
      "secretName",
      "ivBase64",
      "ciphertextBase64",
      "macBase64",
    ],
  );

  @override
  Future<Uint8List> crateSsssDeriveMasterKey({
    required String passphrase,
    required String salt,
    required int iterations,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(passphrase, serializer);
          sse_encode_String(salt, serializer);
          sse_encode_u_32(iterations, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateSsssDeriveMasterKeyConstMeta,
        argValues: [passphrase, salt, iterations],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSsssDeriveMasterKeyConstMeta => const TaskConstMeta(
    debugName: "ssss_derive_master_key",
    argNames: ["passphrase", "salt", "iterations"],
  );

  @override
  Future<EncryptedSecret> crateSsssEncryptSecret({
    required List<int> masterKey,
    required String secretName,
    required String plaintext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(masterKey, serializer);
          sse_encode_String(secretName, serializer);
          sse_encode_String(plaintext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_encrypted_secret,
          decodeErrorData: sse_decode_crypto_error,
        ),
        constMeta: kCrateSsssEncryptSecretConstMeta,
        argValues: [masterKey, secretName, plaintext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSsssEncryptSecretConstMeta => const TaskConstMeta(
    debugName: "ssss_encrypt_secret",
    argNames: ["masterKey", "secretName", "plaintext"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CryptoSession => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CryptoSession => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession;

  @protected
  CryptoSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CryptoSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CryptoSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CryptoSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CryptoSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CryptoSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CrossSigningSecrets dco_decode_box_autoadd_cross_signing_secrets(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_cross_signing_secrets(raw);
  }

  @protected
  PendingRequest dco_decode_box_autoadd_pending_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pending_request(raw);
  }

  @protected
  CrossSigningBootstrap dco_decode_cross_signing_bootstrap(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CrossSigningBootstrap(
      uploadKeysReq: dco_decode_opt_box_autoadd_pending_request(arr[0]),
      uploadSigningKeysReq: dco_decode_pending_request(arr[1]),
      uploadSignaturesReq: dco_decode_pending_request(arr[2]),
    );
  }

  @protected
  CrossSigningSecrets dco_decode_cross_signing_secrets(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CrossSigningSecrets(
      masterKey: dco_decode_opt_String(arr[0]),
      selfSigningKey: dco_decode_opt_String(arr[1]),
      userSigningKey: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  CryptoError dco_decode_crypto_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return CryptoError(message: dco_decode_String(arr[0]));
  }

  @protected
  EncryptedAttachment dco_decode_encrypted_attachment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return EncryptedAttachment(
      ciphertext: dco_decode_list_prim_u_8_strict(arr[0]),
      keyBase64: dco_decode_String(arr[1]),
      ivBase64: dco_decode_String(arr[2]),
      sha256Base64: dco_decode_String(arr[3]),
    );
  }

  @protected
  EncryptedSecret dco_decode_encrypted_secret(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return EncryptedSecret(
      iv: dco_decode_String(arr[0]),
      ciphertext: dco_decode_String(arr[1]),
      mac: dco_decode_String(arr[2]),
    );
  }

  @protected
  IdentityKeys dco_decode_identity_keys(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return IdentityKeys(
      curve25519: dco_decode_String(arr[0]),
      ed25519: dco_decode_String(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<PendingRequest> dco_decode_list_pending_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_pending_request).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, BigInt)> dco_decode_list_record_string_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_u_64).toList();
  }

  @protected
  NewKeyBackup dco_decode_new_key_backup(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NewKeyBackup(
      decryptionKeyBase64: dco_decode_String(arr[0]),
      createVersionBodyJson: dco_decode_String(arr[1]),
    );
  }

  @protected
  NewSecretStorageKey dco_decode_new_secret_storage_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return NewSecretStorageKey(
      keyId: dco_decode_String(arr[0]),
      salt: dco_decode_String(arr[1]),
      iterations: dco_decode_u_32(arr[2]),
      checkIv: dco_decode_String(arr[3]),
      checkMac: dco_decode_String(arr[4]),
      masterKey: dco_decode_list_prim_u_8_strict(arr[5]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  CrossSigningSecrets? dco_decode_opt_box_autoadd_cross_signing_secrets(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_cross_signing_secrets(raw);
  }

  @protected
  PendingRequest? dco_decode_opt_box_autoadd_pending_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_pending_request(raw);
  }

  @protected
  PendingRequest dco_decode_pending_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PendingRequest(
      id: dco_decode_String(arr[0]),
      kind: dco_decode_String(arr[1]),
      method: dco_decode_String(arr[2]),
      path: dco_decode_String(arr[3]),
      bodyJson: dco_decode_String(arr[4]),
    );
  }

  @protected
  (String, BigInt) dco_decode_record_string_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_u_64(arr[1]));
  }

  @protected
  RoomKeyCountsInfo dco_decode_room_key_counts_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RoomKeyCountsInfo(
      total: dco_decode_u_32(arr[0]),
      backedUp: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  CryptoSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CryptoSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CryptoSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CryptoSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CryptoSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CryptoSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CrossSigningSecrets sse_decode_box_autoadd_cross_signing_secrets(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_cross_signing_secrets(deserializer));
  }

  @protected
  PendingRequest sse_decode_box_autoadd_pending_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pending_request(deserializer));
  }

  @protected
  CrossSigningBootstrap sse_decode_cross_signing_bootstrap(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uploadKeysReq = sse_decode_opt_box_autoadd_pending_request(
      deserializer,
    );
    var var_uploadSigningKeysReq = sse_decode_pending_request(deserializer);
    var var_uploadSignaturesReq = sse_decode_pending_request(deserializer);
    return CrossSigningBootstrap(
      uploadKeysReq: var_uploadKeysReq,
      uploadSigningKeysReq: var_uploadSigningKeysReq,
      uploadSignaturesReq: var_uploadSignaturesReq,
    );
  }

  @protected
  CrossSigningSecrets sse_decode_cross_signing_secrets(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_masterKey = sse_decode_opt_String(deserializer);
    var var_selfSigningKey = sse_decode_opt_String(deserializer);
    var var_userSigningKey = sse_decode_opt_String(deserializer);
    return CrossSigningSecrets(
      masterKey: var_masterKey,
      selfSigningKey: var_selfSigningKey,
      userSigningKey: var_userSigningKey,
    );
  }

  @protected
  CryptoError sse_decode_crypto_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_message = sse_decode_String(deserializer);
    return CryptoError(message: var_message);
  }

  @protected
  EncryptedAttachment sse_decode_encrypted_attachment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ciphertext = sse_decode_list_prim_u_8_strict(deserializer);
    var var_keyBase64 = sse_decode_String(deserializer);
    var var_ivBase64 = sse_decode_String(deserializer);
    var var_sha256Base64 = sse_decode_String(deserializer);
    return EncryptedAttachment(
      ciphertext: var_ciphertext,
      keyBase64: var_keyBase64,
      ivBase64: var_ivBase64,
      sha256Base64: var_sha256Base64,
    );
  }

  @protected
  EncryptedSecret sse_decode_encrypted_secret(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_iv = sse_decode_String(deserializer);
    var var_ciphertext = sse_decode_String(deserializer);
    var var_mac = sse_decode_String(deserializer);
    return EncryptedSecret(
      iv: var_iv,
      ciphertext: var_ciphertext,
      mac: var_mac,
    );
  }

  @protected
  IdentityKeys sse_decode_identity_keys(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_curve25519 = sse_decode_String(deserializer);
    var var_ed25519 = sse_decode_String(deserializer);
    return IdentityKeys(curve25519: var_curve25519, ed25519: var_ed25519);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<PendingRequest> sse_decode_list_pending_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PendingRequest>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_pending_request(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, BigInt)> sse_decode_list_record_string_u_64(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, BigInt)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_u_64(deserializer));
    }
    return ans_;
  }

  @protected
  NewKeyBackup sse_decode_new_key_backup(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_decryptionKeyBase64 = sse_decode_String(deserializer);
    var var_createVersionBodyJson = sse_decode_String(deserializer);
    return NewKeyBackup(
      decryptionKeyBase64: var_decryptionKeyBase64,
      createVersionBodyJson: var_createVersionBodyJson,
    );
  }

  @protected
  NewSecretStorageKey sse_decode_new_secret_storage_key(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_keyId = sse_decode_String(deserializer);
    var var_salt = sse_decode_String(deserializer);
    var var_iterations = sse_decode_u_32(deserializer);
    var var_checkIv = sse_decode_String(deserializer);
    var var_checkMac = sse_decode_String(deserializer);
    var var_masterKey = sse_decode_list_prim_u_8_strict(deserializer);
    return NewSecretStorageKey(
      keyId: var_keyId,
      salt: var_salt,
      iterations: var_iterations,
      checkIv: var_checkIv,
      checkMac: var_checkMac,
      masterKey: var_masterKey,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  CrossSigningSecrets? sse_decode_opt_box_autoadd_cross_signing_secrets(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_cross_signing_secrets(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PendingRequest? sse_decode_opt_box_autoadd_pending_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_pending_request(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PendingRequest sse_decode_pending_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_method = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_bodyJson = sse_decode_String(deserializer);
    return PendingRequest(
      id: var_id,
      kind: var_kind,
      method: var_method,
      path: var_path,
      bodyJson: var_bodyJson,
    );
  }

  @protected
  (String, BigInt) sse_decode_record_string_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_u_64(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  RoomKeyCountsInfo sse_decode_room_key_counts_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_total = sse_decode_u_32(deserializer);
    var var_backedUp = sse_decode_u_32(deserializer);
    return RoomKeyCountsInfo(total: var_total, backedUp: var_backedUp);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
    CryptoSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CryptoSessionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
    CryptoSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CryptoSessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
    CryptoSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CryptoSessionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_cross_signing_secrets(
    CrossSigningSecrets self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_cross_signing_secrets(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_pending_request(
    PendingRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pending_request(self, serializer);
  }

  @protected
  void sse_encode_cross_signing_bootstrap(
    CrossSigningBootstrap self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_pending_request(self.uploadKeysReq, serializer);
    sse_encode_pending_request(self.uploadSigningKeysReq, serializer);
    sse_encode_pending_request(self.uploadSignaturesReq, serializer);
  }

  @protected
  void sse_encode_cross_signing_secrets(
    CrossSigningSecrets self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.masterKey, serializer);
    sse_encode_opt_String(self.selfSigningKey, serializer);
    sse_encode_opt_String(self.userSigningKey, serializer);
  }

  @protected
  void sse_encode_crypto_error(CryptoError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_encrypted_attachment(
    EncryptedAttachment self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.ciphertext, serializer);
    sse_encode_String(self.keyBase64, serializer);
    sse_encode_String(self.ivBase64, serializer);
    sse_encode_String(self.sha256Base64, serializer);
  }

  @protected
  void sse_encode_encrypted_secret(
    EncryptedSecret self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.iv, serializer);
    sse_encode_String(self.ciphertext, serializer);
    sse_encode_String(self.mac, serializer);
  }

  @protected
  void sse_encode_identity_keys(IdentityKeys self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.curve25519, serializer);
    sse_encode_String(self.ed25519, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_pending_request(
    List<PendingRequest> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_pending_request(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_u_64(
    List<(String, BigInt)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_u_64(item, serializer);
    }
  }

  @protected
  void sse_encode_new_key_backup(NewKeyBackup self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.decryptionKeyBase64, serializer);
    sse_encode_String(self.createVersionBodyJson, serializer);
  }

  @protected
  void sse_encode_new_secret_storage_key(
    NewSecretStorageKey self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.keyId, serializer);
    sse_encode_String(self.salt, serializer);
    sse_encode_u_32(self.iterations, serializer);
    sse_encode_String(self.checkIv, serializer);
    sse_encode_String(self.checkMac, serializer);
    sse_encode_list_prim_u_8_strict(self.masterKey, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_cross_signing_secrets(
    CrossSigningSecrets? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_cross_signing_secrets(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_pending_request(
    PendingRequest? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_pending_request(self, serializer);
    }
  }

  @protected
  void sse_encode_pending_request(
    PendingRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.method, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.bodyJson, serializer);
  }

  @protected
  void sse_encode_record_string_u_64(
    (String, BigInt) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_u_64(self.$2, serializer);
  }

  @protected
  void sse_encode_room_key_counts_info(
    RoomKeyCountsInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.total, serializer);
    sse_encode_u_32(self.backedUp, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class CryptoSessionImpl extends RustOpaque implements CryptoSession {
  // Not to be used by end users
  CryptoSessionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CryptoSessionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: CluborbitMatrixNative
        .instance
        .api
        .rust_arc_increment_strong_count_CryptoSession,
    rustArcDecrementStrongCount: CluborbitMatrixNative
        .instance
        .api
        .rust_arc_decrement_strong_count_CryptoSession,
    rustArcDecrementStrongCountPtr: CluborbitMatrixNative
        .instance
        .api
        .rust_arc_decrement_strong_count_CryptoSessionPtr,
  );

  /// The next batch (the crypto engine caps it at 100) of room keys not yet in the active
  /// server-side backup, already encrypted to the backup's public key, as a
  /// `PUT /room_keys/keys` request — None when everything is backed up (or no backup is active).
  /// Send it and report back via `mark_request_as_sent` (kind "keys_backup"); repeat until None.
  /// This is what makes every key this device receives or creates recoverable after a reinstall.
  Future<PendingRequest?> backupRoomKeys() => CluborbitMatrixNative.instance.api
      .crateCryptoSessionBackupRoomKeys(that: this);

  /// Creates (or re-publishes) this account's cross-signing identity, matching
  /// cluborbit-web's `crypto.bootstrapCrossSigning()` call in chatService.js — once done, this
  /// device (and any other cross-signed device on the account) shows up as "verified" to other
  /// users instead of relying on per-device trust-on-first-use. Safe to call on every login:
  /// matrix-sdk-crypto only generates new keys the first time; later calls just re-publish the
  /// existing ones. Uploading the signing keys requires user-interactive auth — this preemptively
  /// attaches password auth (the same UIA shortcut chatService.js's authUploadDeviceSigningKeys
  /// takes on retry, just supplied up front instead of after a 401, to skip that extra round
  /// trip), using the same account password already used to log in and to open the crypto store.
  Future<CrossSigningBootstrap> bootstrapCrossSigning({
    required String password,
  }) => CluborbitMatrixNative.instance.api
      .crateCryptoSessionBootstrapCrossSigning(that: this, password: password);

  /// Decrypts an `m.room.encrypted` event, given the room it came from and the full raw event
  /// JSON exactly as received (including type, sender, content, etc. — not just the content).
  /// Returns the decrypted plaintext event content as a JSON string.
  Future<String> decryptRoomEvent({
    required String roomId,
    required String eventJson,
  }) => CluborbitMatrixNative.instance.api.crateCryptoSessionDecryptRoomEvent(
    that: this,
    roomId: roomId,
    eventJson: eventJson,
  );

  /// The device ID this machine was created with, echoed back for sanity-checking from Dart.
  Future<String> deviceId() =>
      CluborbitMatrixNative.instance.api.crateCryptoSessionDeviceId(that: this);

  /// Activates this account's existing server-side key backup using its decryption key
  /// (recovered via SSSS) — `version_info_json` is the raw JSON body of
  /// `GET /room_keys/version`, used both to read the backup's version string and to verify the
  /// key actually matches its published public key before trusting it for anything; a mismatch
  /// (wrong password, or the backup was reset since) makes this a safe no-op instead of
  /// activating against the wrong backup. Returns whether it was activated — call
  /// `import_room_keys_from_backup` next to actually pull the existing keys in.
  Future<bool> enableKeyBackupFromSecret({
    required String decryptionKeyBase64,
    required String versionInfoJson,
  }) => CluborbitMatrixNative.instance.api
      .crateCryptoSessionEnableKeyBackupFromSecret(
        that: this,
        decryptionKeyBase64: decryptionKeyBase64,
        versionInfoJson: versionInfoJson,
      );

  /// Megolm-encrypts a plaintext event for the given room — panics (per matrix-sdk-crypto's own
  /// contract) if `share_room_key` hasn't been called for this room first. `event_type` and
  /// `content_json` are the plaintext event's own type ("m.room.message") and content, exactly
  /// as they'd be sent to an unencrypted room; the returned JSON is the content of the
  /// `m.room.encrypted` event to send instead.
  Future<String> encryptRoomEvent({
    required String roomId,
    required String eventType,
    required String contentJson,
  }) => CluborbitMatrixNative.instance.api.crateCryptoSessionEncryptRoomEvent(
    that: this,
    roomId: roomId,
    eventType: eventType,
    contentJson: contentJson,
  );

  /// Returns the `/keys/claim` request needed to set up 1-to-1 Olm sessions with every device of
  /// the given users that doesn't have one yet, or None when none are missing. This request is
  /// NOT part of `outgoing_requests` — matrix-sdk-crypto hands it back only here — so the caller
  /// must send it and feed the response to `mark_request_as_sent` (kind "keys_claim") before
  /// `share_room_key`, otherwise the room key is silently withheld from those devices and they
  /// show "unable to decrypt".
  Future<PendingRequest?> ensureSessionsForUsers({
    required List<String> userIds,
  }) => CluborbitMatrixNative.instance.api
      .crateCryptoSessionEnsureSessionsForUsers(that: this, userIds: userIds);

  /// This account's private cross-signing keys (unpadded base64 seeds), for storing in newly
  /// created secret storage so other devices can recover the same identity. None if absent.
  Future<CrossSigningSecrets?> exportCrossSigningKeys() => CluborbitMatrixNative
      .instance
      .api
      .crateCryptoSessionExportCrossSigningKeys(that: this);

  /// This device's own Curve25519 (used for Olm sessions) and Ed25519 (used for signing) keys.
  Future<IdentityKeys> identityKeys() => CluborbitMatrixNative.instance.api
      .crateCryptoSessionIdentityKeys(that: this);

  /// Imports this account's private cross-signing keys, recovered via SSSS, instead of
  /// `bootstrap_cross_signing` generating a brand new identity that would conflict with one
  /// another device (like cluborbit-web) already published — call this first, and only fall
  /// back to `bootstrap_cross_signing` if this account's secret storage has none of these secrets
  /// stored yet (a genuinely first-ever setup). Each argument is that secret's decrypted
  /// plaintext (an unpadded base64 Ed25519 seed, via `ssss_decrypt_secret`) — pass whichever of
  /// the three were actually present; matrix-sdk-crypto imports only the ones given. Returns
  /// whether the identity is now fully usable (all three present, locally, after this import).
  Future<bool> importCrossSigningKeys({
    String? masterKey,
    String? selfSigningKey,
    String? userSigningKey,
  }) => CluborbitMatrixNative.instance.api
      .crateCryptoSessionImportCrossSigningKeys(
        that: this,
        masterKey: masterKey,
        selfSigningKey: selfSigningKey,
        userSigningKey: userSigningKey,
      );

  /// The second half of restoring an existing backup: given the raw JSON body of
  /// `GET /room_keys/keys?version=<version>` (fetch this only after `enable_key_backup_from_secret`
  /// returned true), decrypts every session with the now-active backup decryption key and
  /// imports them — this is what actually makes message history from before this device existed
  /// readable again. Returns how many session keys were imported.
  Future<int> importRoomKeysFromBackup({required String keysResponseJson}) =>
      CluborbitMatrixNative.instance.api
          .crateCryptoSessionImportRoomKeysFromBackup(
            that: this,
            keysResponseJson: keysResponseJson,
          );

  /// Whether this account's cross-signing identity (master + self-signing + user-signing keys)
  /// is already set up — check this before calling `bootstrap_cross_signing` to skip the extra
  /// request round trip on every login after the first.
  Future<bool> isCrossSigningReady() => CluborbitMatrixNative.instance.api
      .crateCryptoSessionIsCrossSigningReady(that: this);

  /// Whether a server-side key backup is active on this machine (so `backup_room_keys` uploads).
  Future<bool> isKeyBackupEnabled() => CluborbitMatrixNative.instance.api
      .crateCryptoSessionIsKeyBackupEnabled(that: this);

  /// Feeds the HTTP response for a request `outgoing_requests` handed you back into the
  /// machine, identified by the same id/kind pair. Must be called for every request returned by
  /// `outgoing_requests` (skipping one — e.g. because the HTTP call failed — just means it'll be
  /// handed back again next time `outgoing_requests` is called).
  Future<void> markRequestAsSent({
    required String id,
    required String kind,
    required String responseJson,
  }) => CluborbitMatrixNative.instance.api.crateCryptoSessionMarkRequestAsSent(
    that: this,
    id: id,
    kind: kind,
    responseJson: responseJson,
  );

  /// Generates a brand-new backup key and the signed body for `POST /room_keys/version` - only
  /// for when the account has no usable backup at all. The caller stores the returned decryption
  /// key in secret storage (as `m.megolm_backup.v1`) and then activates it with
  /// `enable_key_backup_from_secret`, exactly like a restored backup.
  Future<NewKeyBackup> newKeyBackup() => CluborbitMatrixNative.instance.api
      .crateCryptoSessionNewKeyBackup(that: this);

  /// Requests that need to be sent to the homeserver right now — call this after every
  /// meaningful state change (after `create`, after `receive_sync_changes`, after
  /// `share_room_key`) and send each one, then report the result back via
  /// `mark_request_as_sent`. Mirrors the same "drain outgoing requests" loop chatService.js
  /// doesn't need to do explicitly because matrix-js-sdk's higher-level Client drives it
  /// internally — here we're one layer lower, so the Dart side has to drive it.
  Future<List<PendingRequest>> outgoingRequests() => CluborbitMatrixNative
      .instance
      .api
      .crateCryptoSessionOutgoingRequests(that: this);

  /// Feeds one `/sync` response's crypto-relevant pieces into the machine: to-device events
  /// (each as a raw JSON string, exactly as received), the user IDs whose device lists changed
  /// or left, and the one-time-key counts per algorithm (e.g. {"signed_curve25519": 47}).
  /// Returns the to-device events that were actually processed (decrypted where needed) as JSON
  /// strings, for the Dart side to hand to whatever already deals with to-device events (key
  /// verification requests, etc.).
  Future<List<String>> receiveSyncChanges({
    required List<String> toDeviceEventsJson,
    required List<String> changedDeviceUsers,
    required List<String> leftDeviceUsers,
    required List<(String, BigInt)> oneTimeKeyCounts,
  }) => CluborbitMatrixNative.instance.api.crateCryptoSessionReceiveSyncChanges(
    that: this,
    toDeviceEventsJson: toDeviceEventsJson,
    changedDeviceUsers: changedDeviceUsers,
    leftDeviceUsers: leftDeviceUsers,
    oneTimeKeyCounts: oneTimeKeyCounts,
  );

  /// How many room keys this store holds, and how many of those are in the active backup.
  Future<RoomKeyCountsInfo> roomKeyCounts() => CluborbitMatrixNative
      .instance
      .api
      .crateCryptoSessionRoomKeyCounts(that: this);

  /// Shares this room's current outbound Megolm session with the given users, rotating to a new
  /// one first if none exists yet or the old one needs rotating — matching how
  /// cluborbit-web's client.sendMessage implicitly does this via matrix-js-sdk before every send
  /// to a room whose key hasn't been shared with a member yet. `ensure_sessions_for_users` must
  /// have already been called (and its resulting keys_claim round trip completed) for these
  /// users, or sharing will simply skip devices with no session.
  ///
  /// Returns the to-device requests that actually carry the room key. Like keys_claim, these are
  /// NOT part of `outgoing_requests` — matrix-sdk-crypto hands them back only here — so the caller
  /// must send every one and feed each response to `mark_request_as_sent` (kind "to_device").
  /// Dropping them means the key never leaves this device and every recipient sees "unable to
  /// decrypt" for everything this device sends.
  Future<List<PendingRequest>> shareRoomKey({
    required String roomId,
    required List<String> userIds,
  }) => CluborbitMatrixNative.instance.api.crateCryptoSessionShareRoomKey(
    that: this,
    roomId: roomId,
    userIds: userIds,
  );

  /// Adds the given users (room members) to the machine's tracked-users list, flagging any not
  /// seen before for an immediate `/keys/query` — which then comes out of the next
  /// `outgoing_requests` drain. Without this the machine only ever knows about devices of users
  /// that happened to show up in a sync's `device_lists.changed`, so a room key would never be
  /// shared with anyone else's devices. Call this (then drain) before `ensure_sessions_for_users`.
  Future<void> updateTrackedUsers({required List<String> userIds}) =>
      CluborbitMatrixNative.instance.api.crateCryptoSessionUpdateTrackedUsers(
        that: this,
        userIds: userIds,
      );
}
