// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class CluborbitMatrixNativeApiImplPlatform
    extends BaseApiImpl<CluborbitMatrixNativeWire> {
  CluborbitMatrixNativeApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CryptoSessionPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSessionPtr;

  @protected
  CryptoSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
    dynamic raw,
  );

  @protected
  CryptoSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
    dynamic raw,
  );

  @protected
  CryptoSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CrossSigningSecrets dco_decode_box_autoadd_cross_signing_secrets(dynamic raw);

  @protected
  PendingRequest dco_decode_box_autoadd_pending_request(dynamic raw);

  @protected
  CrossSigningBootstrap dco_decode_cross_signing_bootstrap(dynamic raw);

  @protected
  CrossSigningSecrets dco_decode_cross_signing_secrets(dynamic raw);

  @protected
  CryptoError dco_decode_crypto_error(dynamic raw);

  @protected
  EncryptedAttachment dco_decode_encrypted_attachment(dynamic raw);

  @protected
  EncryptedSecret dco_decode_encrypted_secret(dynamic raw);

  @protected
  IdentityKeys dco_decode_identity_keys(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<PendingRequest> dco_decode_list_pending_request(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, BigInt)> dco_decode_list_record_string_u_64(dynamic raw);

  @protected
  NewKeyBackup dco_decode_new_key_backup(dynamic raw);

  @protected
  NewSecretStorageKey dco_decode_new_secret_storage_key(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CrossSigningSecrets? dco_decode_opt_box_autoadd_cross_signing_secrets(
    dynamic raw,
  );

  @protected
  PendingRequest? dco_decode_opt_box_autoadd_pending_request(dynamic raw);

  @protected
  PendingRequest dco_decode_pending_request(dynamic raw);

  @protected
  (String, BigInt) dco_decode_record_string_u_64(dynamic raw);

  @protected
  RoomKeyCountsInfo dco_decode_room_key_counts_info(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  CryptoSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
    SseDeserializer deserializer,
  );

  @protected
  CryptoSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
    SseDeserializer deserializer,
  );

  @protected
  CryptoSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CrossSigningSecrets sse_decode_box_autoadd_cross_signing_secrets(
    SseDeserializer deserializer,
  );

  @protected
  PendingRequest sse_decode_box_autoadd_pending_request(
    SseDeserializer deserializer,
  );

  @protected
  CrossSigningBootstrap sse_decode_cross_signing_bootstrap(
    SseDeserializer deserializer,
  );

  @protected
  CrossSigningSecrets sse_decode_cross_signing_secrets(
    SseDeserializer deserializer,
  );

  @protected
  CryptoError sse_decode_crypto_error(SseDeserializer deserializer);

  @protected
  EncryptedAttachment sse_decode_encrypted_attachment(
    SseDeserializer deserializer,
  );

  @protected
  EncryptedSecret sse_decode_encrypted_secret(SseDeserializer deserializer);

  @protected
  IdentityKeys sse_decode_identity_keys(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<PendingRequest> sse_decode_list_pending_request(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, BigInt)> sse_decode_list_record_string_u_64(
    SseDeserializer deserializer,
  );

  @protected
  NewKeyBackup sse_decode_new_key_backup(SseDeserializer deserializer);

  @protected
  NewSecretStorageKey sse_decode_new_secret_storage_key(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CrossSigningSecrets? sse_decode_opt_box_autoadd_cross_signing_secrets(
    SseDeserializer deserializer,
  );

  @protected
  PendingRequest? sse_decode_opt_box_autoadd_pending_request(
    SseDeserializer deserializer,
  );

  @protected
  PendingRequest sse_decode_pending_request(SseDeserializer deserializer);

  @protected
  (String, BigInt) sse_decode_record_string_u_64(SseDeserializer deserializer);

  @protected
  RoomKeyCountsInfo sse_decode_room_key_counts_info(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
    CryptoSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
    CryptoSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
    CryptoSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_cross_signing_secrets(
    CrossSigningSecrets self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pending_request(
    PendingRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cross_signing_bootstrap(
    CrossSigningBootstrap self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cross_signing_secrets(
    CrossSigningSecrets self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_crypto_error(CryptoError self, SseSerializer serializer);

  @protected
  void sse_encode_encrypted_attachment(
    EncryptedAttachment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_encrypted_secret(
    EncryptedSecret self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_identity_keys(IdentityKeys self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_pending_request(
    List<PendingRequest> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_u_64(
    List<(String, BigInt)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_new_key_backup(NewKeyBackup self, SseSerializer serializer);

  @protected
  void sse_encode_new_secret_storage_key(
    NewSecretStorageKey self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_cross_signing_secrets(
    CrossSigningSecrets? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_pending_request(
    PendingRequest? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pending_request(
    PendingRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_u_64(
    (String, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_room_key_counts_info(
    RoomKeyCountsInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class CluborbitMatrixNativeWire implements BaseWire {
  factory CluborbitMatrixNativeWire.fromExternalLibrary(ExternalLibrary lib) =>
      CluborbitMatrixNativeWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  CluborbitMatrixNativeWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_cluborbit_matrix_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_cluborbit_matrix_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSession =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
