// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cross_signing_key_to_raw`, `outgoing_request_entry`, `parse_response`, `request_to_pending`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`, `fmt`, `fmt`, `from`, `from`

/// Trivial call with no crypto involved — the first thing to wire up and call from Dart, purely
/// to prove the Rust ⇄ Dart ⇄ (eventually) Android .so pipeline works before layering in
/// anything that actually touches key material.
Future<String> nativeCryptoEngineVersion() =>
    CluborbitMatrixNative.instance.api.crateNativeCryptoEngineVersion();

/// Step 1: turns the account password into this account's 32-byte 4S master key, given the
/// iterations/salt published (in the clear) on this account's `m.secret_storage.key.<id>` event.
Future<Uint8List> ssssDeriveMasterKey({
  required String passphrase,
  required String salt,
  required int iterations,
}) => CluborbitMatrixNative.instance.api.crateSsssDeriveMasterKey(
  passphrase: passphrase,
  salt: salt,
  iterations: iterations,
);

/// Verifies a derived master key against the same `m.secret_storage.key.<id>` event's published
/// check value, before it's trusted for anything — a wrong password (or salt/iterations pulled
/// from the wrong key id) simply returns false here rather than going on to decrypt anything.
Future<bool> ssssCheckMasterKey({
  required List<int> masterKey,
  required String checkIvBase64,
  required String expectedMacBase64,
}) => CluborbitMatrixNative.instance.api.crateSsssCheckMasterKey(
  masterKey: masterKey,
  checkIvBase64: checkIvBase64,
  expectedMacBase64: expectedMacBase64,
);

/// Decrypts one secret-storage item — `secret_name` must be the secret's own account-data event
/// type (e.g. "m.megolm_backup.v1", "m.cross_signing.master"), and iv/ciphertext/mac come from
/// that event's `content.encrypted.<keyId>` payload.
Future<String> ssssDecryptSecret({
  required List<int> masterKey,
  required String secretName,
  required String ivBase64,
  required String ciphertextBase64,
  required String macBase64,
}) => CluborbitMatrixNative.instance.api.crateSsssDecryptSecret(
  masterKey: masterKey,
  secretName: secretName,
  ivBase64: ivBase64,
  ciphertextBase64: ciphertextBase64,
  macBase64: macBase64,
);

Future<NewSecretStorageKey> ssssCreateKeyFromPassphrase({
  required String passphrase,
}) => CluborbitMatrixNative.instance.api.crateSsssCreateKeyFromPassphrase(
  passphrase: passphrase,
);

/// Encrypts one secret (e.g. "m.megolm_backup.v1") for storing in account data - the inverse of
/// `ssss_decrypt_secret`.
Future<EncryptedSecret> ssssEncryptSecret({
  required List<int> masterKey,
  required String secretName,
  required String plaintext,
}) => CluborbitMatrixNative.instance.api.crateSsssEncryptSecret(
  masterKey: masterKey,
  secretName: secretName,
  plaintext: plaintext,
);

/// Encrypts a media attachment (image/video/file/audio bytes) before upload, per the Matrix
/// spec's "Sending encrypted attachments" — matches cluborbit-web's own attachment encryption
/// byte-for-byte (see rust/src/attachment_crypto.rs), so a photo sent from either client decrypts
/// correctly on the other.
Future<EncryptedAttachment> encryptAttachment({required List<int> plaintext}) =>
    CluborbitMatrixNative.instance.api.crateEncryptAttachment(
      plaintext: plaintext,
    );

/// Decrypts a downloaded attachment ciphertext using the `key`/`iv` from the event's `content.file`
/// — `sha256_base64` should be `content.file.hashes.sha256` when present (it always is for an
/// attachment this app or any spec-compliant Matrix client produced); verified before decrypting,
/// never skipped when available.
Future<Uint8List> decryptAttachment({
  required List<int> ciphertext,
  required String keyBase64,
  required String ivBase64,
  String? sha256Base64,
}) => CluborbitMatrixNative.instance.api.crateDecryptAttachment(
  ciphertext: ciphertext,
  keyBase64: keyBase64,
  ivBase64: ivBase64,
  sha256Base64: sha256Base64,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CryptoSession>>
abstract class CryptoSession implements RustOpaqueInterface {
  /// The next batch (the crypto engine caps it at 100) of room keys not yet in the active
  /// server-side backup, already encrypted to the backup's public key, as a
  /// `PUT /room_keys/keys` request — None when everything is backed up (or no backup is active).
  /// Send it and report back via `mark_request_as_sent` (kind "keys_backup"); repeat until None.
  /// This is what makes every key this device receives or creates recoverable after a reinstall.
  Future<PendingRequest?> backupRoomKeys();

  /// Creates (or re-publishes) this account's cross-signing identity, matching
  /// cluborbit-web's `crypto.bootstrapCrossSigning()` call in chatService.js — once done, this
  /// device (and any other cross-signed device on the account) shows up as "verified" to other
  /// users instead of relying on per-device trust-on-first-use. Safe to call on every login:
  /// matrix-sdk-crypto only generates new keys the first time; later calls just re-publish the
  /// existing ones. Uploading the signing keys requires user-interactive auth — this preemptively
  /// attaches password auth (the same UIA shortcut chatService.js's authUploadDeviceSigningKeys
  /// takes on retry, just supplied up front instead of after a 401, to skip that extra round
  /// trip), using the same account password already used to log in and to open the crypto store.
  Future<CrossSigningBootstrap> bootstrapCrossSigning({
    required String password,
  });

  /// Opens (creating if needed) a SQLite-backed OlmMachine for (user_id, device_id) rooted at
  /// store_path — a directory the Dart side is responsible for pointing at somewhere private
  /// and durable (path_provider's app-support directory, matching how cluborbit-web namespaces
  /// its IndexedDB store per-uid). passphrase encrypts the store at rest; pass the Club Orbit
  /// account password the same way chatService.js derives its secret-storage key from it, so
  /// there's nothing new for the user to remember.
  static Future<CryptoSession> create({
    required String userId,
    required String deviceId,
    required String storePath,
    required String passphrase,
  }) => CluborbitMatrixNative.instance.api.crateCryptoSessionCreate(
    userId: userId,
    deviceId: deviceId,
    storePath: storePath,
    passphrase: passphrase,
  );

  /// Decrypts an `m.room.encrypted` event, given the room it came from and the full raw event
  /// JSON exactly as received (including type, sender, content, etc. — not just the content).
  /// Returns the decrypted plaintext event content as a JSON string.
  Future<String> decryptRoomEvent({
    required String roomId,
    required String eventJson,
  });

  /// The device ID this machine was created with, echoed back for sanity-checking from Dart.
  Future<String> deviceId();

  /// Activates this account's existing server-side key backup using its decryption key
  /// (recovered via SSSS) — `version_info_json` is the raw JSON body of
  /// `GET /room_keys/version`, used both to read the backup's version string and to verify the
  /// key actually matches its published public key before trusting it for anything; a mismatch
  /// (wrong password, or the backup was reset since) makes this a safe no-op instead of
  /// activating against the wrong backup. Returns whether it was activated — call
  /// `import_room_keys_from_backup` next to actually pull the existing keys in.
  Future<bool> enableKeyBackupFromSecret({
    required String decryptionKeyBase64,
    required String versionInfoJson,
  });

  /// Megolm-encrypts a plaintext event for the given room — panics (per matrix-sdk-crypto's own
  /// contract) if `share_room_key` hasn't been called for this room first. `event_type` and
  /// `content_json` are the plaintext event's own type ("m.room.message") and content, exactly
  /// as they'd be sent to an unencrypted room; the returned JSON is the content of the
  /// `m.room.encrypted` event to send instead.
  Future<String> encryptRoomEvent({
    required String roomId,
    required String eventType,
    required String contentJson,
  });

  /// Returns the `/keys/claim` request needed to set up 1-to-1 Olm sessions with every device of
  /// the given users that doesn't have one yet, or None when none are missing. This request is
  /// NOT part of `outgoing_requests` — matrix-sdk-crypto hands it back only here — so the caller
  /// must send it and feed the response to `mark_request_as_sent` (kind "keys_claim") before
  /// `share_room_key`, otherwise the room key is silently withheld from those devices and they
  /// show "unable to decrypt".
  Future<PendingRequest?> ensureSessionsForUsers({
    required List<String> userIds,
  });

  /// This account's private cross-signing keys (unpadded base64 seeds), for storing in newly
  /// created secret storage so other devices can recover the same identity. None if absent.
  Future<CrossSigningSecrets?> exportCrossSigningKeys();

  /// This device's own Curve25519 (used for Olm sessions) and Ed25519 (used for signing) keys.
  Future<IdentityKeys> identityKeys();

  /// Imports this account's private cross-signing keys, recovered via SSSS, instead of
  /// `bootstrap_cross_signing` generating a brand new identity that would conflict with one
  /// another device (like cluborbit-web) already published — call this first, and only fall
  /// back to `bootstrap_cross_signing` if this account's secret storage has none of these secrets
  /// stored yet (a genuinely first-ever setup). Each argument is that secret's decrypted
  /// plaintext (an unpadded base64 Ed25519 seed, via `ssss_decrypt_secret`) — pass whichever of
  /// the three were actually present; matrix-sdk-crypto imports only the ones given. Returns
  /// whether the identity is now fully usable (all three present, locally, after this import).
  Future<bool> importCrossSigningKeys({
    String? masterKey,
    String? selfSigningKey,
    String? userSigningKey,
  });

  /// The second half of restoring an existing backup: given the raw JSON body of
  /// `GET /room_keys/keys?version=<version>` (fetch this only after `enable_key_backup_from_secret`
  /// returned true), decrypts every session with the now-active backup decryption key and
  /// imports them — this is what actually makes message history from before this device existed
  /// readable again. Returns how many session keys were imported.
  Future<int> importRoomKeysFromBackup({required String keysResponseJson});

  /// Whether this account's cross-signing identity (master + self-signing + user-signing keys)
  /// is already set up — check this before calling `bootstrap_cross_signing` to skip the extra
  /// request round trip on every login after the first.
  Future<bool> isCrossSigningReady();

  /// Whether a server-side key backup is active on this machine (so `backup_room_keys` uploads).
  Future<bool> isKeyBackupEnabled();

  /// Feeds the HTTP response for a request `outgoing_requests` handed you back into the
  /// machine, identified by the same id/kind pair. Must be called for every request returned by
  /// `outgoing_requests` (skipping one — e.g. because the HTTP call failed — just means it'll be
  /// handed back again next time `outgoing_requests` is called).
  Future<void> markRequestAsSent({
    required String id,
    required String kind,
    required String responseJson,
  });

  /// Generates a brand-new backup key and the signed body for `POST /room_keys/version` - only
  /// for when the account has no usable backup at all. The caller stores the returned decryption
  /// key in secret storage (as `m.megolm_backup.v1`) and then activates it with
  /// `enable_key_backup_from_secret`, exactly like a restored backup.
  Future<NewKeyBackup> newKeyBackup();

  /// Requests that need to be sent to the homeserver right now — call this after every
  /// meaningful state change (after `create`, after `receive_sync_changes`, after
  /// `share_room_key`) and send each one, then report the result back via
  /// `mark_request_as_sent`. Mirrors the same "drain outgoing requests" loop chatService.js
  /// doesn't need to do explicitly because matrix-js-sdk's higher-level Client drives it
  /// internally — here we're one layer lower, so the Dart side has to drive it.
  Future<List<PendingRequest>> outgoingRequests();

  /// Feeds one `/sync` response's crypto-relevant pieces into the machine: to-device events
  /// (each as a raw JSON string, exactly as received), the user IDs whose device lists changed
  /// or left, and the one-time-key counts per algorithm (e.g. {"signed_curve25519": 47}).
  /// Returns the to-device events that were actually processed (decrypted where needed) as JSON
  /// strings, for the Dart side to hand to whatever already deals with to-device events (key
  /// verification requests, etc.).
  Future<List<String>> receiveSyncChanges({
    required List<String> toDeviceEventsJson,
    required List<String> changedDeviceUsers,
    required List<String> leftDeviceUsers,
    required List<(String, BigInt)> oneTimeKeyCounts,
  });

  /// How many room keys this store holds, and how many of those are in the active backup.
  Future<RoomKeyCountsInfo> roomKeyCounts();

  /// Shares this room's current outbound Megolm session with the given users, rotating to a new
  /// one first if none exists yet or the old one needs rotating — matching how
  /// cluborbit-web's client.sendMessage implicitly does this via matrix-js-sdk before every send
  /// to a room whose key hasn't been shared with a member yet. `ensure_sessions_for_users` must
  /// have already been called (and its resulting keys_claim round trip completed) for these
  /// users, or sharing will simply skip devices with no session.
  ///
  /// Returns the to-device requests that actually carry the room key. Like keys_claim, these are
  /// NOT part of `outgoing_requests` — matrix-sdk-crypto hands them back only here — so the caller
  /// must send every one and feed each response to `mark_request_as_sent` (kind "to_device").
  /// Dropping them means the key never leaves this device and every recipient sees "unable to
  /// decrypt" for everything this device sends.
  Future<List<PendingRequest>> shareRoomKey({
    required String roomId,
    required List<String> userIds,
  });

  /// Adds the given users (room members) to the machine's tracked-users list, flagging any not
  /// seen before for an immediate `/keys/query` — which then comes out of the next
  /// `outgoing_requests` drain. Without this the machine only ever knows about devices of users
  /// that happened to show up in a sync's `device_lists.changed`, so a room key would never be
  /// shared with anyone else's devices. Call this (then drain) before `ensure_sessions_for_users`.
  Future<void> updateTrackedUsers({required List<String> userIds});
}

/// The requests `bootstrap_cross_signing` needs sent, in order: device keys (if any are still
/// missing) first, then the cross-signing keys themselves, then the signatures that tie them
/// together. Each must be sent and fed back through `mark_request_as_sent` in that order, same as
/// `outgoing_requests`'s results.
class CrossSigningBootstrap {
  final PendingRequest? uploadKeysReq;
  final PendingRequest uploadSigningKeysReq;
  final PendingRequest uploadSignaturesReq;

  const CrossSigningBootstrap({
    this.uploadKeysReq,
    required this.uploadSigningKeysReq,
    required this.uploadSignaturesReq,
  });

  @override
  int get hashCode =>
      uploadKeysReq.hashCode ^
      uploadSigningKeysReq.hashCode ^
      uploadSignaturesReq.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CrossSigningBootstrap &&
          runtimeType == other.runtimeType &&
          uploadKeysReq == other.uploadKeysReq &&
          uploadSigningKeysReq == other.uploadSigningKeysReq &&
          uploadSignaturesReq == other.uploadSignaturesReq;
}

class CrossSigningSecrets {
  final String? masterKey;
  final String? selfSigningKey;
  final String? userSigningKey;

  const CrossSigningSecrets({
    this.masterKey,
    this.selfSigningKey,
    this.userSigningKey,
  });

  @override
  int get hashCode =>
      masterKey.hashCode ^ selfSigningKey.hashCode ^ userSigningKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CrossSigningSecrets &&
          runtimeType == other.runtimeType &&
          masterKey == other.masterKey &&
          selfSigningKey == other.selfSigningKey &&
          userSigningKey == other.userSigningKey;
}

class CryptoError implements FrbException {
  final String message;

  const CryptoError({required this.message});

  @override
  int get hashCode => message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CryptoError &&
          runtimeType == other.runtimeType &&
          message == other.message;
}

/// The result of `encrypt_attachment` — everything the `m.room.message` event's `file` field
/// needs (the `EncryptedFile` object from the Matrix spec) except `url`, which the Dart side fills
/// in once the ciphertext has actually been uploaded to the media repo.
class EncryptedAttachment {
  final Uint8List ciphertext;
  final String keyBase64;
  final String ivBase64;
  final String sha256Base64;

  const EncryptedAttachment({
    required this.ciphertext,
    required this.keyBase64,
    required this.ivBase64,
    required this.sha256Base64,
  });

  @override
  int get hashCode =>
      ciphertext.hashCode ^
      keyBase64.hashCode ^
      ivBase64.hashCode ^
      sha256Base64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptedAttachment &&
          runtimeType == other.runtimeType &&
          ciphertext == other.ciphertext &&
          keyBase64 == other.keyBase64 &&
          ivBase64 == other.ivBase64 &&
          sha256Base64 == other.sha256Base64;
}

/// `{iv, ciphertext, mac}` for one secret, ready for `content.encrypted.<keyId>`.
class EncryptedSecret {
  final String iv;
  final String ciphertext;
  final String mac;

  const EncryptedSecret({
    required this.iv,
    required this.ciphertext,
    required this.mac,
  });

  @override
  int get hashCode => iv.hashCode ^ ciphertext.hashCode ^ mac.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptedSecret &&
          runtimeType == other.runtimeType &&
          iv == other.iv &&
          ciphertext == other.ciphertext &&
          mac == other.mac;
}

/// This device's own identity keys — surfaced so the app can show them for manual verification
/// (matching the "Start key verification" flow cluborbit-web already has) and for debug logging.
class IdentityKeys {
  final String curve25519;
  final String ed25519;

  const IdentityKeys({required this.curve25519, required this.ed25519});

  @override
  int get hashCode => curve25519.hashCode ^ ed25519.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityKeys &&
          runtimeType == other.runtimeType &&
          curve25519 == other.curve25519 &&
          ed25519 == other.ed25519;
}

class NewKeyBackup {
  final String decryptionKeyBase64;
  final String createVersionBodyJson;

  const NewKeyBackup({
    required this.decryptionKeyBase64,
    required this.createVersionBodyJson,
  });

  @override
  int get hashCode =>
      decryptionKeyBase64.hashCode ^ createVersionBodyJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewKeyBackup &&
          runtimeType == other.runtimeType &&
          decryptionKeyBase64 == other.decryptionKeyBase64 &&
          createVersionBodyJson == other.createVersionBodyJson;
}

/// A newly created, password-derived secret-storage key - for an account that has none yet. The
/// Dart side publishes `m.secret_storage.key.<key_id>` (algorithm, passphrase {m.pbkdf2, salt,
/// iterations, bits: 256}, iv, mac) and `m.secret_storage.default_key`, then encrypts secrets
/// with `master_key`. Same scheme and parameters as cluborbit-web's
/// createRecoveryKeyFromPassphrase (500,000 PBKDF2-SHA512 iterations, 32-char salt), so the web
/// derives the identical key from the same password and can read everything stored under it.
class NewSecretStorageKey {
  final String keyId;
  final String salt;
  final int iterations;
  final String checkIv;
  final String checkMac;
  final Uint8List masterKey;

  const NewSecretStorageKey({
    required this.keyId,
    required this.salt,
    required this.iterations,
    required this.checkIv,
    required this.checkMac,
    required this.masterKey,
  });

  @override
  int get hashCode =>
      keyId.hashCode ^
      salt.hashCode ^
      iterations.hashCode ^
      checkIv.hashCode ^
      checkMac.hashCode ^
      masterKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewSecretStorageKey &&
          runtimeType == other.runtimeType &&
          keyId == other.keyId &&
          salt == other.salt &&
          iterations == other.iterations &&
          checkIv == other.checkIv &&
          checkMac == other.checkMac &&
          masterKey == other.masterKey;
}

class PendingRequest {
  /// Echoed back to `mark_request_as_sent` once the HTTP call completes — matrix-sdk-crypto uses
  /// this to match a response to the request that produced it.
  final String id;

  /// Which of the fixed set of request kinds this is (e.g. "keys_upload") — also echoed back,
  /// so `mark_request_as_sent` knows which response type to parse the JSON as.
  final String kind;
  final String method;
  final String path;
  final String bodyJson;

  const PendingRequest({
    required this.id,
    required this.kind,
    required this.method,
    required this.path,
    required this.bodyJson,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      method.hashCode ^
      path.hashCode ^
      bodyJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingRequest &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          method == other.method &&
          path == other.path &&
          bodyJson == other.bodyJson;
}

class RoomKeyCountsInfo {
  final int total;
  final int backedUp;

  const RoomKeyCountsInfo({required this.total, required this.backedUp});

  @override
  int get hashCode => total.hashCode ^ backedUp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomKeyCountsInfo &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          backedUp == other.backedUp;
}
