// Native crypto engine for the Flutter app, bridged to Dart via flutter_rust_bridge.
//
// This wraps `matrix-sdk-crypto` — the same Apache-2.0 crate whose WASM build
// (`@matrix-org/matrix-sdk-crypto-wasm`) already powers cluborbit-web's end-to-end encryption —
// so both clients share one audited crypto implementation instead of two separate ones. The API
// surface here intentionally mirrors the lifecycle cluborbit-web's chatService.js already
// implements (see that file for the reference behavior each of these is meant to match):
//   1. create/load a persistent OlmMachine for this device
//   2. feed it sync data (device list changes, to-device messages, one-time-key counts)
//   3. share/receive Megolm room keys
//   4. encrypt outgoing room events / decrypt incoming ones
//   5. cross-signing + secret storage + key backup, so history is readable across devices
//
// Status: step 1 of that list (persistent machine creation + identity keys) plus the
// flutter_rust_bridge scaffolding itself (this file's frb_generated module, regenerated by
// `flutter_rust_bridge_codegen generate` whenever the public API below changes — never hand-edit
// frb_generated.rs/.dart). Not yet run against a live homeserver; `cargo build`/`cargo test` are
// the only verification available in this environment so far.
//
// NOTE: `mod frb_generated;` must stay as the very first item in this file — plain `//` comments
// (not `//!` inner doc comments) are used here specifically so codegen re-injecting that line up
// top never breaks the build the way an inner doc comment would.
mod frb_generated;
mod attachment_crypto;
mod secret_storage;

use matrix_sdk_crypto::olm::{BackedUpRoomKey, EncryptionSettings};
use matrix_sdk_crypto::store::types::{BackupDecryptionKey, CrossSigningKeyExport};
use matrix_sdk_crypto::types::events::room::encrypted::EncryptedEvent;
use matrix_sdk_crypto::types::requests::{
    AnyIncomingResponse as CryptoAnyIncomingResponse, AnyOutgoingRequest,
};
use matrix_sdk_crypto::types::RoomKeyBackupInfo;
use matrix_sdk_crypto::{DecryptionSettings, EncryptionSyncChanges, OlmMachine, TrustRequirement};
use ruma::api::client::backup::{add_backup_keys, get_backup_keys};
use ruma::api::client::keys::{claim_keys, get_keys, upload_keys, upload_signatures, upload_signing_keys};
use ruma::api::client::to_device::send_event_to_device;
use ruma::api::client::uiaa::{AuthData, Password as UiaaPassword, UserIdentifier};
use ruma::api::{IncomingResponse, MatrixVersion, OutgoingRequest, SendAccessToken};
use ruma::events::AnyToDeviceEvent;
use ruma::serde::Raw;
use ruma::{DeviceId, OneTimeKeyAlgorithm, OwnedRoomId, RoomId, TransactionId, UserId};
use std::collections::BTreeMap;

/// Converts an outgoing API request (whatever ruma-typed struct a specific endpoint uses) into a
/// method + path + JSON body — Dart's REST client already knows how to make an authenticated HTTP
/// call given those three things, so this keeps every endpoint-specific detail (exact path,
/// method, how fields map to the wire body) inside Rust, checked against ruma's real types,
/// instead of duplicated by hand in Dart. base_url is a placeholder — the real one lives in Dart's
/// client config — since only the path is kept from the result.
fn request_to_pending<R: OutgoingRequest>(id: String, kind: &str, req: R) -> Result<PendingRequest, CryptoError> {
    let http_req: http::Request<Vec<u8>> = req
        .try_into_http_request(
            "https://dummy.invalid",
            SendAccessToken::IfRequired("unused"),
            &[MatrixVersion::V1_1],
        )
        .map_err(|e| CryptoError { message: e.to_string() })?;
    let method = http_req.method().to_string();
    let path = http_req.uri().path_and_query().map(|pq| pq.to_string()).unwrap_or_default();
    let body_json = String::from_utf8(http_req.into_body()).map_err(|e| CryptoError { message: e.to_string() })?;
    Ok(PendingRequest { id, kind: kind.to_string(), method, path, body_json })
}

/// The inverse: parses the JSON body Dart got back from the homeserver into the typed response a
/// specific endpoint expects, via the same ruma machinery in reverse.
fn parse_response<R: IncomingResponse>(response_json: String) -> Result<R, CryptoError> {
    let http_response = http::Response::builder()
        .status(200)
        .body(response_json.into_bytes())
        .map_err(|e| CryptoError { message: e.to_string() })?;
    R::try_from_http_response(http_response).map_err(|e| CryptoError { message: e.to_string() })
}

/// Re-tags a matrix-sdk-crypto `CrossSigningKey` (its own mirror of the wire type, produced by
/// `bootstrap_cross_signing`) as `Raw<ruma's CrossSigningKey>` for the upload request — `Raw` is
/// just phantom-typed JSON text, so a plain serialize/re-tag round trip is enough; the two types
/// are guaranteed to share the same JSON shape (that's the entire point of matrix-sdk-crypto's
/// mirror types), no field-by-field conversion needed.
fn cross_signing_key_to_raw(
    key: &matrix_sdk_crypto::types::CrossSigningKey,
) -> Result<Raw<ruma::encryption::CrossSigningKey>, CryptoError> {
    Ok(Raw::from_json_string(serde_json::to_string(key)?)?)
}

/// Converts one of the machine's queued outgoing requests into the method/path/body shape Dart
/// sends over HTTP — shared between `outgoing_requests` (the normal per-sync pump) and
/// `bootstrap_cross_signing` (which hands back an `AnyOutgoingRequest` for the device-key upload
/// outside that pump, using the exact same request type).
fn outgoing_request_entry(id: String, request: &AnyOutgoingRequest) -> Result<Option<PendingRequest>, CryptoError> {
    Ok(match request {
        AnyOutgoingRequest::KeysUpload(req) => Some(request_to_pending(id, "keys_upload", req.clone())?),
        AnyOutgoingRequest::KeysQuery(req) => {
            // matrix-sdk-crypto's KeysQueryRequest is a "customized version" of ruma's own
            // get_keys::v3::Request (its own doc comment says so) with identical fields, so build
            // one of those from it — only the real ruma type implements OutgoingRequest, which is
            // what actually knows the correct wire shape/path.
            let ruma_request = {
                // #[non_exhaustive] blocks struct-literal syntax (even with ..Default::default())
                // from outside the defining crate — build via Default then assign fields instead.
                let mut r = get_keys::v3::Request::default();
                r.timeout = req.timeout;
                r.device_keys = req.device_keys.clone();
                r
            };
            Some(request_to_pending(id, "keys_query", ruma_request)?)
        }
        AnyOutgoingRequest::KeysClaim(req) => Some(request_to_pending(id, "keys_claim", req.clone())?),
        AnyOutgoingRequest::ToDeviceRequest(req) => {
            // Same story as KeysQuery — matrix-sdk-crypto's ToDeviceRequest is its own "customized
            // version" of ruma's send_event_to_device::v3::Request with matching fields.
            let ruma_request = send_event_to_device::v3::Request::new_raw(
                req.event_type.clone(),
                req.txn_id.clone(),
                req.messages.clone(),
            );
            Some(request_to_pending(id, "to_device", ruma_request)?)
        }
        AnyOutgoingRequest::SignatureUpload(req) => {
            Some(request_to_pending(id, "signature_upload", req.clone())?)
        }
        // RoomMessage (interactive-verification-in-room) isn't needed without a verification UI.
        AnyOutgoingRequest::RoomMessage(_) => None,
    })
}

/// One device's crypto state — the Rust-side handle Dart holds onto for every other call. Opaque
/// to Dart (flutter_rust_bridge generates a thin wrapper around a pointer to this), since an
/// OlmMachine can't be meaningfully copied or serialized.
pub struct CryptoSession {
    // ManuallyDrop so Drop (below) can release it inside the async runtime.
    machine: std::mem::ManuallyDrop<OlmMachine>,
    // The runtime this session was created on (flutter_rust_bridge's async executor).
    runtime: Option<tokio::runtime::Handle>,
}

impl Drop for CryptoSession {
    /// Dart releases this handle from its own thread (dispose(), or the GC finalizer), where no
    /// tokio runtime is active - but the SQLite store's connection pool can only be dropped
    /// inside one, and dropping it outside aborts the whole process (which silently killed the
    /// closed-app notification decrypt). So enter the creating runtime for the drop.
    fn drop(&mut self) {
        let _guard = self.runtime.as_ref().map(|handle| handle.enter());
        // SAFETY: dropped exactly once, here, and never accessed afterwards.
        unsafe { std::mem::ManuallyDrop::drop(&mut self.machine) };
    }
}

/// This device's own identity keys — surfaced so the app can show them for manual verification
/// (matching the "Start key verification" flow cluborbit-web already has) and for debug logging.
pub struct IdentityKeys {
    pub curve25519: String,
    pub ed25519: String,
}

#[derive(Debug)]
pub struct CryptoError {
    pub message: String,
}

impl std::fmt::Display for CryptoError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}
impl std::error::Error for CryptoError {}

// No blanket `impl<E: Display> From<E> for CryptoError` here — it collides with the standard
// library's own reflexive `impl<T> From<T> for T`. Call sites use `.map_err(CryptoError::from)`
// against these specific conversions instead.
impl From<ruma::IdParseError> for CryptoError {
    fn from(err: ruma::IdParseError) -> Self {
        CryptoError { message: err.to_string() }
    }
}
impl From<serde_json::Error> for CryptoError {
    fn from(err: serde_json::Error) -> Self {
        CryptoError { message: err.to_string() }
    }
}

// matrix-sdk-crypto is deliberately transport-agnostic — it hands back abstract "requests" you're
// responsible for actually sending, then hands the response back in. This is that pump, generic
// over every request kind the machine can produce: Dart's REST client (matrix_low_level_client.dart)
// already knows how to make an authenticated HTTP call given a method/path/body, so this keeps ALL
// Matrix-protocol-specific knowledge (which endpoint, which HTTP method, how the body is shaped —
// some request types serialize directly, others need their fields remapped into the real wire
// shape) inside Rust, where it's checked against ruma's real types, rather than duplicated in Dart.
pub struct PendingRequest {
    /// Echoed back to `mark_request_as_sent` once the HTTP call completes — matrix-sdk-crypto uses
    /// this to match a response to the request that produced it.
    pub id: String,
    /// Which of the fixed set of request kinds this is (e.g. "keys_upload") — also echoed back,
    /// so `mark_request_as_sent` knows which response type to parse the JSON as.
    pub kind: String,
    pub method: String,
    pub path: String,
    pub body_json: String,
}

/// The requests `bootstrap_cross_signing` needs sent, in order: device keys (if any are still
/// missing) first, then the cross-signing keys themselves, then the signatures that tie them
/// together. Each must be sent and fed back through `mark_request_as_sent` in that order, same as
/// `outgoing_requests`'s results.
pub struct CrossSigningBootstrap {
    pub upload_keys_req: Option<PendingRequest>,
    pub upload_signing_keys_req: PendingRequest,
    pub upload_signatures_req: PendingRequest,
}

impl CryptoSession {
    /// Requests that need to be sent to the homeserver right now — call this after every
    /// meaningful state change (after `create`, after `receive_sync_changes`, after
    /// `share_room_key`) and send each one, then report the result back via
    /// `mark_request_as_sent`. Mirrors the same "drain outgoing requests" loop chatService.js
    /// doesn't need to do explicitly because matrix-js-sdk's higher-level Client drives it
    /// internally — here we're one layer lower, so the Dart side has to drive it.
    pub async fn outgoing_requests(&self) -> Result<Vec<PendingRequest>, CryptoError> {
        let requests =
            self.machine.outgoing_requests().await.map_err(|e| CryptoError { message: e.to_string() })?;

        let mut pending = Vec::new();
        for request in requests {
            let id = request.request_id().to_string();
            if let Some(entry) = outgoing_request_entry(id, request.request())? {
                pending.push(entry);
            }
        }

        Ok(pending)
    }

    /// Feeds the HTTP response for a request `outgoing_requests` handed you back into the
    /// machine, identified by the same id/kind pair. Must be called for every request returned by
    /// `outgoing_requests` (skipping one — e.g. because the HTTP call failed — just means it'll be
    /// handed back again next time `outgoing_requests` is called).
    pub async fn mark_request_as_sent(
        &self,
        id: String,
        kind: String,
        response_json: String,
    ) -> Result<(), CryptoError> {
        let request_id: &TransactionId = id.as_str().into();
        match kind.as_str() {
            "keys_upload" => {
                let response = parse_response::<upload_keys::v3::Response>(response_json)?;
                self.machine
                    .mark_request_as_sent(request_id, &response)
                    .await
                    .map_err(|e| CryptoError { message: e.to_string() })?;
            }
            "keys_query" => {
                let response = parse_response::<get_keys::v3::Response>(response_json)?;
                self.machine
                    .mark_request_as_sent(request_id, &response)
                    .await
                    .map_err(|e| CryptoError { message: e.to_string() })?;
            }
            "keys_claim" => {
                let response = parse_response::<claim_keys::v3::Response>(response_json)?;
                self.machine
                    .mark_request_as_sent(request_id, &response)
                    .await
                    .map_err(|e| CryptoError { message: e.to_string() })?;
            }
            "to_device" => {
                let response = parse_response::<send_event_to_device::v3::Response>(response_json)?;
                self.machine
                    .mark_request_as_sent(request_id, &response)
                    .await
                    .map_err(|e| CryptoError { message: e.to_string() })?;
            }
            "signature_upload" => {
                let response = parse_response::<upload_signatures::v3::Response>(response_json)?;
                self.machine
                    .mark_request_as_sent(request_id, &response)
                    .await
                    .map_err(|e| CryptoError { message: e.to_string() })?;
            }
            "keys_backup" => {
                let response = parse_response::<add_backup_keys::v3::Response>(response_json)?;
                self.machine
                    .mark_request_as_sent(request_id, &response)
                    .await
                    .map_err(|e| CryptoError { message: e.to_string() })?;
            }
            "signing_keys_upload" => {
                // No `From<&Response> for AnyIncomingResponse` impl exists for this one (unlike
                // every other kind above) — construct the variant directly instead.
                let response = parse_response::<upload_signing_keys::v3::Response>(response_json)?;
                self.machine
                    .mark_request_as_sent(request_id, CryptoAnyIncomingResponse::SigningKeysUpload(&response))
                    .await
                    .map_err(|e| CryptoError { message: e.to_string() })?;
            }
            other => {
                return Err(CryptoError { message: format!("Unknown request kind: {other}") });
            }
        }
        Ok(())
    }

    /// Feeds one `/sync` response's crypto-relevant pieces into the machine: to-device events
    /// (each as a raw JSON string, exactly as received), the user IDs whose device lists changed
    /// or left, and the one-time-key counts per algorithm (e.g. {"signed_curve25519": 47}).
    /// Returns the to-device events that were actually processed (decrypted where needed) as JSON
    /// strings, for the Dart side to hand to whatever already deals with to-device events (key
    /// verification requests, etc.).
    pub async fn receive_sync_changes(
        &self,
        to_device_events_json: Vec<String>,
        changed_device_users: Vec<String>,
        left_device_users: Vec<String>,
        // (algorithm, count) pairs rather than a BTreeMap<String, u64> — flutter_rust_bridge has
        // no simple-type support for BTreeMap and opaque-wraps it instead, which leaves Dart with
        // no way to actually construct one to pass in here. A list of pairs is a plain Dart
        // List<(String, int)>, buildable directly from the sync response's JSON map.
        one_time_key_counts: Vec<(String, u64)>,
    ) -> Result<Vec<String>, CryptoError> {
        let to_device_events: Vec<Raw<AnyToDeviceEvent>> = to_device_events_json
            .iter()
            .map(|json| Raw::from_json_string(json.clone()))
            .collect::<Result<_, _>>()?;

        let changed: Vec<_> =
            changed_device_users.iter().map(|u| UserId::parse(u.as_str())).collect::<Result<_, _>>()?;
        let left: Vec<_> =
            left_device_users.iter().map(|u| UserId::parse(u.as_str())).collect::<Result<_, _>>()?;
        let mut device_lists = ruma::api::client::sync::sync_events::DeviceLists::default();
        device_lists.changed = changed;
        device_lists.left = left;

        let key_counts: BTreeMap<OneTimeKeyAlgorithm, ruma::UInt> = one_time_key_counts
            .into_iter()
            .map(|(k, v)| (OneTimeKeyAlgorithm::from(k), ruma::UInt::new(v).unwrap_or_default()))
            .collect();

        let changes = EncryptionSyncChanges {
            to_device_events,
            changed_devices: &device_lists,
            one_time_keys_counts: &key_counts,
            unused_fallback_keys: None,
            next_batch_token: None,
        };

        let (events, _room_key_updates) = self
            .machine
            .receive_sync_changes(changes)
            .await
            .map_err(|e| CryptoError { message: e.to_string() })?;

        Ok(events.iter().map(|e| e.as_raw().json().get().to_string()).collect())
    }

    /// Adds the given users (room members) to the machine's tracked-users list, flagging any not
    /// seen before for an immediate `/keys/query` — which then comes out of the next
    /// `outgoing_requests` drain. Without this the machine only ever knows about devices of users
    /// that happened to show up in a sync's `device_lists.changed`, so a room key would never be
    /// shared with anyone else's devices. Call this (then drain) before `ensure_sessions_for_users`.
    pub async fn update_tracked_users(&self, user_ids: Vec<String>) -> Result<(), CryptoError> {
        let users: Vec<_> = user_ids.iter().map(|u| UserId::parse(u.as_str())).collect::<Result<_, _>>()?;
        // Boxed as an owned `dyn Future + Send`: update_tracked_users' future borrows the user IDs,
        // which trips rustc's higher-ranked Send check inside flutter_rust_bridge's async wrapper.
        let machine = self.machine.clone();
        let fut: std::pin::Pin<Box<dyn std::future::Future<Output = _> + Send>> = Box::pin(async move {
            let user_refs: Vec<&UserId> = users.iter().map(|u| &**u).collect();
            machine.update_tracked_users(user_refs).await
        });
        fut.await.map_err(|e| CryptoError { message: e.to_string() })?;
        Ok(())
    }

    /// Returns the `/keys/claim` request needed to set up 1-to-1 Olm sessions with every device of
    /// the given users that doesn't have one yet, or None when none are missing. This request is
    /// NOT part of `outgoing_requests` — matrix-sdk-crypto hands it back only here — so the caller
    /// must send it and feed the response to `mark_request_as_sent` (kind "keys_claim") before
    /// `share_room_key`, otherwise the room key is silently withheld from those devices and they
    /// show "unable to decrypt".
    pub async fn ensure_sessions_for_users(&self, user_ids: Vec<String>) -> Result<Option<PendingRequest>, CryptoError> {
        let users: Vec<_> = user_ids.iter().map(|u| UserId::parse(u.as_str())).collect::<Result<_, _>>()?;
        let user_refs: Vec<&UserId> = users.iter().map(|u| u.as_ref()).collect();
        let missing = self
            .machine
            .get_missing_sessions(user_refs.iter().copied())
            .await
            .map_err(|e| CryptoError { message: e.to_string() })?;
        match missing {
            Some((txn_id, request)) => Ok(Some(request_to_pending(txn_id.to_string(), "keys_claim", request)?)),
            None => Ok(None),
        }
    }

    /// Shares this room's current outbound Megolm session with the given users, rotating to a new
    /// one first if none exists yet or the old one needs rotating — matching how
    /// cluborbit-web's client.sendMessage implicitly does this via matrix-js-sdk before every send
    /// to a room whose key hasn't been shared with a member yet. `ensure_sessions_for_users` must
    /// have already been called (and its resulting keys_claim round trip completed) for these
    /// users, or sharing will simply skip devices with no session.
    ///
    /// Returns the to-device requests that actually carry the room key. Like keys_claim, these are
    /// NOT part of `outgoing_requests` — matrix-sdk-crypto hands them back only here — so the caller
    /// must send every one and feed each response to `mark_request_as_sent` (kind "to_device").
    /// Dropping them means the key never leaves this device and every recipient sees "unable to
    /// decrypt" for everything this device sends.
    pub async fn share_room_key(&self, room_id: String, user_ids: Vec<String>) -> Result<Vec<PendingRequest>, CryptoError> {
        let room_id = <&RoomId>::try_from(room_id.as_str())
            .map_err(|e: ruma::IdParseError| CryptoError { message: e.to_string() })?;
        let users: Vec<_> = user_ids.iter().map(|u| UserId::parse(u.as_str())).collect::<Result<_, _>>()?;
        let requests = self
            .machine
            .share_room_key(room_id, users.iter().map(|u| u.as_ref()), EncryptionSettings::default())
            .await
            .map_err(|e| CryptoError { message: e.to_string() })?;
        let mut pending = Vec::with_capacity(requests.len());
        for req in requests {
            // Same conversion outgoing_request_entry does for queued to-device requests; the txn_id
            // doubles as the request id mark_request_as_sent expects.
            let ruma_request = send_event_to_device::v3::Request::new_raw(
                req.event_type.clone(),
                req.txn_id.clone(),
                req.messages.clone(),
            );
            pending.push(request_to_pending(req.txn_id.to_string(), "to_device", ruma_request)?);
        }
        Ok(pending)
    }

    /// Megolm-encrypts a plaintext event for the given room — panics (per matrix-sdk-crypto's own
    /// contract) if `share_room_key` hasn't been called for this room first. `event_type` and
    /// `content_json` are the plaintext event's own type ("m.room.message") and content, exactly
    /// as they'd be sent to an unencrypted room; the returned JSON is the content of the
    /// `m.room.encrypted` event to send instead.
    pub async fn encrypt_room_event(
        &self,
        room_id: String,
        event_type: String,
        content_json: String,
    ) -> Result<String, CryptoError> {
        let room_id = <&RoomId>::try_from(room_id.as_str())
            .map_err(|e: ruma::IdParseError| CryptoError { message: e.to_string() })?;
        let content: Raw<ruma::events::AnyMessageLikeEventContent> =
            Raw::from_json_string(content_json)?;
        let encrypted = self
            .machine
            .encrypt_room_event_raw(room_id, event_type.as_str(), &content)
            .await
            .map_err(|e| CryptoError { message: e.to_string() })?;
        Ok(encrypted.json().get().to_string())
    }

    /// Decrypts an `m.room.encrypted` event, given the room it came from and the full raw event
    /// JSON exactly as received (including type, sender, content, etc. — not just the content).
    /// Returns the decrypted plaintext event content as a JSON string.
    pub async fn decrypt_room_event(&self, room_id: String, event_json: String) -> Result<String, CryptoError> {
        let room_id = <&RoomId>::try_from(room_id.as_str())
            .map_err(|e: ruma::IdParseError| CryptoError { message: e.to_string() })?;
        let event: Raw<EncryptedEvent> = Raw::from_json_string(event_json)?;
        // Untrusted: decrypt regardless of the sender device's cross-signing state — matches how
        // cluborbit-web currently behaves too (verification isn't enforced as a precondition for
        // decryption there either yet).
        let decryption_settings =
            DecryptionSettings { sender_device_trust_requirement: TrustRequirement::Untrusted };
        let decrypted = self
            .machine
            .decrypt_room_event(&event, room_id, &decryption_settings)
            .await
            .map_err(|e| CryptoError { message: e.to_string() })?;
        Ok(decrypted.event.json().get().to_string())
    }

    /// Whether this account's cross-signing identity (master + self-signing + user-signing keys)
    /// is already set up — check this before calling `bootstrap_cross_signing` to skip the extra
    /// request round trip on every login after the first.
    pub async fn is_cross_signing_ready(&self) -> bool {
        self.machine.cross_signing_status().await.is_complete()
    }

    /// Creates (or re-publishes) this account's cross-signing identity, matching
    /// cluborbit-web's `crypto.bootstrapCrossSigning()` call in chatService.js — once done, this
    /// device (and any other cross-signed device on the account) shows up as "verified" to other
    /// users instead of relying on per-device trust-on-first-use. Safe to call on every login:
    /// matrix-sdk-crypto only generates new keys the first time; later calls just re-publish the
    /// existing ones. Uploading the signing keys requires user-interactive auth — this preemptively
    /// attaches password auth (the same UIA shortcut chatService.js's authUploadDeviceSigningKeys
    /// takes on retry, just supplied up front instead of after a 401, to skip that extra round
    /// trip), using the same account password already used to log in and to open the crypto store.
    pub async fn bootstrap_cross_signing(&self, password: String) -> Result<CrossSigningBootstrap, CryptoError> {
        let requests = self
            .machine
            .bootstrap_cross_signing(false)
            .await
            .map_err(|e| CryptoError { message: e.to_string() })?;

        let upload_keys_req = match &requests.upload_keys_req {
            Some(req) => outgoing_request_entry(req.request_id().to_string(), req.request())?,
            None => None,
        };

        let signing = requests.upload_signing_keys_req;
        let mut signing_req = upload_signing_keys::v3::Request::new();
        signing_req.master_key = signing.master_key.as_ref().map(cross_signing_key_to_raw).transpose()?;
        signing_req.self_signing_key =
            signing.self_signing_key.as_ref().map(cross_signing_key_to_raw).transpose()?;
        signing_req.user_signing_key =
            signing.user_signing_key.as_ref().map(cross_signing_key_to_raw).transpose()?;
        signing_req.auth = Some(AuthData::Password(UiaaPassword::new(
            UserIdentifier::UserIdOrLocalpart(self.machine.user_id().to_string()),
            password,
        )));
        let upload_signing_keys_req =
            request_to_pending(TransactionId::new().to_string(), "signing_keys_upload", signing_req)?;

        let upload_signatures_req = request_to_pending(
            TransactionId::new().to_string(),
            "signature_upload",
            requests.upload_signatures_req,
        )?;

        Ok(CrossSigningBootstrap { upload_keys_req, upload_signing_keys_req, upload_signatures_req })
    }

    /// Imports this account's private cross-signing keys, recovered via SSSS, instead of
    /// `bootstrap_cross_signing` generating a brand new identity that would conflict with one
    /// another device (like cluborbit-web) already published — call this first, and only fall
    /// back to `bootstrap_cross_signing` if this account's secret storage has none of these secrets
    /// stored yet (a genuinely first-ever setup). Each argument is that secret's decrypted
    /// plaintext (an unpadded base64 Ed25519 seed, via `ssss_decrypt_secret`) — pass whichever of
    /// the three were actually present; matrix-sdk-crypto imports only the ones given. Returns
    /// whether the identity is now fully usable (all three present, locally, after this import).
    pub async fn import_cross_signing_keys(
        &self,
        master_key: Option<String>,
        self_signing_key: Option<String>,
        user_signing_key: Option<String>,
    ) -> Result<bool, CryptoError> {
        let export = CrossSigningKeyExport { master_key, self_signing_key, user_signing_key };
        let status = self
            .machine
            .import_cross_signing_keys(export)
            .await
            .map_err(|e| CryptoError { message: e.to_string() })?;
        Ok(status.is_complete())
    }

    /// Activates this account's existing server-side key backup using its decryption key
    /// (recovered via SSSS) — `version_info_json` is the raw JSON body of
    /// `GET /room_keys/version`, used both to read the backup's version string and to verify the
    /// key actually matches its published public key before trusting it for anything; a mismatch
    /// (wrong password, or the backup was reset since) makes this a safe no-op instead of
    /// activating against the wrong backup. Returns whether it was activated — call
    /// `import_room_keys_from_backup` next to actually pull the existing keys in.
    pub async fn enable_key_backup_from_secret(
        &self,
        decryption_key_base64: String,
        version_info_json: String,
    ) -> Result<bool, CryptoError> {
        let key = BackupDecryptionKey::from_base64(&decryption_key_base64)
            .map_err(|e| CryptoError { message: e.to_string() })?;

        #[derive(serde::Deserialize)]
        struct VersionField {
            version: String,
        }
        let version_field: VersionField = serde_json::from_str(&version_info_json)?;
        let info: RoomKeyBackupInfo = serde_json::from_str(&version_info_json)?;

        if !key.backup_key_matches(&info) {
            return Ok(false);
        }

        self.machine
            .backup_machine()
            .save_decryption_key(Some(key.clone()), Some(version_field.version.clone()))
            .await
            .map_err(|e| CryptoError { message: e.to_string() })?;

        let public_key = key.megolm_v1_public_key();
        public_key.set_version(version_field.version);
        self.machine
            .backup_machine()
            .enable_backup_v1(public_key)
            .await
            .map_err(|e| CryptoError { message: e.to_string() })?;

        Ok(true)
    }

    /// The second half of restoring an existing backup: given the raw JSON body of
    /// `GET /room_keys/keys?version=<version>` (fetch this only after `enable_key_backup_from_secret`
    /// returned true), decrypts every session with the now-active backup decryption key and
    /// imports them — this is what actually makes message history from before this device existed
    /// readable again. Returns how many session keys were imported.
    pub async fn import_room_keys_from_backup(&self, keys_response_json: String) -> Result<u32, CryptoError> {
        let backup_keys = self
            .machine
            .backup_machine()
            .get_backup_keys()
            .await
            .map_err(|e| CryptoError { message: e.to_string() })?;
        let decryption_key = backup_keys.decryption_key.ok_or_else(|| CryptoError {
            message: "No backup decryption key is active — call enable_key_backup_from_secret first".to_string(),
        })?;

        let response: get_backup_keys::v3::Response = parse_response(keys_response_json)?;

        let mut room_keys: BTreeMap<OwnedRoomId, BTreeMap<String, BackedUpRoomKey>> = BTreeMap::new();
        for (room_id, room_backup) in response.rooms {
            let mut sessions = BTreeMap::new();
            for (session_id, raw_data) in room_backup.sessions {
                let Ok(data) = raw_data.deserialize() else { continue };
                if let Ok(backed_up) = decryption_key.decrypt_session_data(data.session_data) {
                    sessions.insert(session_id, backed_up);
                }
            }
            if !sessions.is_empty() {
                room_keys.insert(room_id, sessions);
            }
        }

        #[allow(deprecated)]
        let result = self
            .machine
            .backup_machine()
            .import_backed_up_room_keys(room_keys, |_, _| {})
            .await
            .map_err(|e| CryptoError { message: e.to_string() })?;

        Ok(result.imported_count as u32)
    }

    /// Whether a server-side key backup is active on this machine (so `backup_room_keys` uploads).
    pub async fn is_key_backup_enabled(&self) -> bool {
        self.machine.backup_machine().enabled().await
    }

    /// The next batch (the crypto engine caps it at 100) of room keys not yet in the active
    /// server-side backup, already encrypted to the backup's public key, as a
    /// `PUT /room_keys/keys` request — None when everything is backed up (or no backup is active).
    /// Send it and report back via `mark_request_as_sent` (kind "keys_backup"); repeat until None.
    /// This is what makes every key this device receives or creates recoverable after a reinstall.
    pub async fn backup_room_keys(&self) -> Result<Option<PendingRequest>, CryptoError> {
        let Some((txn_id, request)) = self
            .machine
            .backup_machine()
            .backup()
            .await
            .map_err(|e| CryptoError { message: e.to_string() })?
        else {
            return Ok(None);
        };
        let ruma_request = add_backup_keys::v3::Request::new(request.version, request.rooms);
        Ok(Some(request_to_pending(txn_id.to_string(), "keys_backup", ruma_request)?))
    }

    /// How many room keys this store holds, and how many of those are in the active backup.
    pub async fn room_key_counts(&self) -> Result<RoomKeyCountsInfo, CryptoError> {
        let counts = self
            .machine
            .backup_machine()
            .room_key_counts()
            .await
            .map_err(|e| CryptoError { message: e.to_string() })?;
        Ok(RoomKeyCountsInfo { total: counts.total as u32, backed_up: counts.backed_up as u32 })
    }

    /// Generates a brand-new backup key and the signed body for `POST /room_keys/version` - only
    /// for when the account has no usable backup at all. The caller stores the returned decryption
    /// key in secret storage (as `m.megolm_backup.v1`) and then activates it with
    /// `enable_key_backup_from_secret`, exactly like a restored backup.
    pub async fn new_key_backup(&self) -> Result<NewKeyBackup, CryptoError> {
        let key = BackupDecryptionKey::new().map_err(|e| CryptoError { message: e.to_string() })?;
        let mut info = key.to_backup_info();
        self.machine
            .backup_machine()
            .sign_backup(&mut info)
            .await
            .map_err(|e| CryptoError { message: e.to_string() })?;
        Ok(NewKeyBackup {
            decryption_key_base64: key.to_base64(),
            create_version_body_json: serde_json::to_string(&info)?,
        })
    }

    /// This account's private cross-signing keys (unpadded base64 seeds), for storing in newly
    /// created secret storage so other devices can recover the same identity. None if absent.
    pub async fn export_cross_signing_keys(&self) -> Result<Option<CrossSigningSecrets>, CryptoError> {
        let export = self
            .machine
            .export_cross_signing_keys()
            .await
            .map_err(|e| CryptoError { message: e.to_string() })?;
        Ok(export.map(|e| CrossSigningSecrets {
            master_key: e.master_key.clone(),
            self_signing_key: e.self_signing_key.clone(),
            user_signing_key: e.user_signing_key.clone(),
        }))
    }
}

pub struct RoomKeyCountsInfo {
    pub total: u32,
    pub backed_up: u32,
}

pub struct NewKeyBackup {
    pub decryption_key_base64: String,
    pub create_version_body_json: String,
}

pub struct CrossSigningSecrets {
    pub master_key: Option<String>,
    pub self_signing_key: Option<String>,
    pub user_signing_key: Option<String>,
}

impl CryptoSession {
    /// Opens (creating if needed) a SQLite-backed OlmMachine for (user_id, device_id) rooted at
    /// store_path — a directory the Dart side is responsible for pointing at somewhere private
    /// and durable (path_provider's app-support directory, matching how cluborbit-web namespaces
    /// its IndexedDB store per-uid). passphrase encrypts the store at rest; pass the Club Orbit
    /// account password the same way chatService.js derives its secret-storage key from it, so
    /// there's nothing new for the user to remember.
    pub async fn create(
        user_id: String,
        device_id: String,
        store_path: String,
        passphrase: String,
    ) -> Result<CryptoSession, CryptoError> {
        let user_id = UserId::parse(user_id.as_str())?;
        let device_id: &DeviceId = device_id.as_str().into();
        let store = matrix_sdk_sqlite::SqliteCryptoStore::open(store_path, Some(passphrase.as_str()))
            .await
            .map_err(|e| CryptoError { message: e.to_string() })?;
        let machine = OlmMachine::with_store(&user_id, device_id, store, None)
            .await
            .map_err(|e| CryptoError { message: e.to_string() })?;
        Ok(CryptoSession {
            machine: std::mem::ManuallyDrop::new(machine),
            runtime: tokio::runtime::Handle::try_current().ok(),
        })
    }

    /// This device's own Curve25519 (used for Olm sessions) and Ed25519 (used for signing) keys.
    pub fn identity_keys(&self) -> IdentityKeys {
        let keys = self.machine.identity_keys();
        IdentityKeys {
            curve25519: keys.curve25519.to_base64(),
            ed25519: keys.ed25519.to_base64(),
        }
    }

    /// The device ID this machine was created with, echoed back for sanity-checking from Dart.
    pub fn device_id(&self) -> String {
        self.machine.device_id().to_string()
    }
}

/// Trivial call with no crypto involved — the first thing to wire up and call from Dart, purely
/// to prove the Rust ⇄ Dart ⇄ (eventually) Android .so pipeline works before layering in
/// anything that actually touches key material.
pub fn native_crypto_engine_version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

// Free functions (not tied to a CryptoSession) implementing Secure Secret Storage and Sharing
// (SSSS / "4S") — see secret_storage.rs for the byte-level spec this is matched against. These
// don't touch the OlmMachine at all: Dart fetches the relevant account-data events itself
// (MatrixLowLevelClient.getAccountData) and calls these to do the actual key derivation/
// decryption, then hands the results to CryptoSession's import_cross_signing_keys /
// enable_key_backup_from_secret for the parts that do need the machine.

/// Step 1: turns the account password into this account's 32-byte 4S master key, given the
/// iterations/salt published (in the clear) on this account's `m.secret_storage.key.<id>` event.
pub fn ssss_derive_master_key(passphrase: String, salt: String, iterations: u32) -> Vec<u8> {
    secret_storage::derive_master_key_from_passphrase(&passphrase, &salt, iterations).to_vec()
}

/// Verifies a derived master key against the same `m.secret_storage.key.<id>` event's published
/// check value, before it's trusted for anything — a wrong password (or salt/iterations pulled
/// from the wrong key id) simply returns false here rather than going on to decrypt anything.
pub fn ssss_check_master_key(master_key: Vec<u8>, check_iv_base64: String, expected_mac_base64: String) -> bool {
    let Ok(key) = <[u8; 32]>::try_from(master_key.as_slice()) else { return false };
    secret_storage::check_master_key(&key, &check_iv_base64, &expected_mac_base64)
}

/// Decrypts one secret-storage item — `secret_name` must be the secret's own account-data event
/// type (e.g. "m.megolm_backup.v1", "m.cross_signing.master"), and iv/ciphertext/mac come from
/// that event's `content.encrypted.<keyId>` payload.
pub fn ssss_decrypt_secret(
    master_key: Vec<u8>,
    secret_name: String,
    iv_base64: String,
    ciphertext_base64: String,
    mac_base64: String,
) -> Result<String, CryptoError> {
    let key = <[u8; 32]>::try_from(master_key.as_slice())
        .map_err(|_| CryptoError { message: "SSSS master key must be 32 bytes".to_string() })?;
    let payload = secret_storage::EncryptedPayload {
        iv: iv_base64,
        ciphertext: ciphertext_base64,
        mac: mac_base64,
    };
    secret_storage::decrypt_secret(&payload, &key, &secret_name)
}

/// A newly created, password-derived secret-storage key - for an account that has none yet. The
/// Dart side publishes `m.secret_storage.key.<key_id>` (algorithm, passphrase {m.pbkdf2, salt,
/// iterations, bits: 256}, iv, mac) and `m.secret_storage.default_key`, then encrypts secrets
/// with `master_key`. Same scheme and parameters as cluborbit-web's
/// createRecoveryKeyFromPassphrase (500,000 PBKDF2-SHA512 iterations, 32-char salt), so the web
/// derives the identical key from the same password and can read everything stored under it.
pub struct NewSecretStorageKey {
    pub key_id: String,
    pub salt: String,
    pub iterations: u32,
    pub check_iv: String,
    pub check_mac: String,
    pub master_key: Vec<u8>,
}

pub fn ssss_create_key_from_passphrase(passphrase: String) -> NewSecretStorageKey {
    const ITERATIONS: u32 = 500_000;
    let salt = secret_storage::random_string(32);
    let master_key = secret_storage::derive_master_key_from_passphrase(&passphrase, &salt, ITERATIONS);
    let check = secret_storage::key_check(&master_key);
    NewSecretStorageKey {
        key_id: secret_storage::random_string(32),
        salt,
        iterations: ITERATIONS,
        check_iv: check.iv,
        check_mac: check.mac,
        master_key: master_key.to_vec(),
    }
}

/// `{iv, ciphertext, mac}` for one secret, ready for `content.encrypted.<keyId>`.
pub struct EncryptedSecret {
    pub iv: String,
    pub ciphertext: String,
    pub mac: String,
}

/// Encrypts one secret (e.g. "m.megolm_backup.v1") for storing in account data - the inverse of
/// `ssss_decrypt_secret`.
pub fn ssss_encrypt_secret(
    master_key: Vec<u8>,
    secret_name: String,
    plaintext: String,
) -> Result<EncryptedSecret, CryptoError> {
    let key = <[u8; 32]>::try_from(master_key.as_slice())
        .map_err(|_| CryptoError { message: "SSSS master key must be 32 bytes".to_string() })?;
    let payload = secret_storage::encrypt_secret(&key, &secret_name, plaintext.as_bytes());
    Ok(EncryptedSecret { iv: payload.iv, ciphertext: payload.ciphertext, mac: payload.mac })
}

/// The result of `encrypt_attachment` — everything the `m.room.message` event's `file` field
/// needs (the `EncryptedFile` object from the Matrix spec) except `url`, which the Dart side fills
/// in once the ciphertext has actually been uploaded to the media repo.
pub struct EncryptedAttachment {
    pub ciphertext: Vec<u8>,
    pub key_base64: String,
    pub iv_base64: String,
    pub sha256_base64: String,
}

/// Encrypts a media attachment (image/video/file/audio bytes) before upload, per the Matrix
/// spec's "Sending encrypted attachments" — matches cluborbit-web's own attachment encryption
/// byte-for-byte (see rust/src/attachment_crypto.rs), so a photo sent from either client decrypts
/// correctly on the other.
pub fn encrypt_attachment(plaintext: Vec<u8>) -> EncryptedAttachment {
    let result = attachment_crypto::encrypt_attachment(&plaintext);
    EncryptedAttachment {
        ciphertext: result.ciphertext,
        key_base64: result.key_base64,
        iv_base64: result.iv_base64,
        sha256_base64: result.sha256_base64,
    }
}

/// Decrypts a downloaded attachment ciphertext using the `key`/`iv` from the event's `content.file`
/// — `sha256_base64` should be `content.file.hashes.sha256` when present (it always is for an
/// attachment this app or any spec-compliant Matrix client produced); verified before decrypting,
/// never skipped when available.
pub fn decrypt_attachment(
    ciphertext: Vec<u8>,
    key_base64: String,
    iv_base64: String,
    sha256_base64: Option<String>,
) -> Result<Vec<u8>, CryptoError> {
    attachment_crypto::decrypt_attachment(&ciphertext, &key_base64, &iv_base64, sha256_base64.as_deref())
}
